// @generated by `cargo xtask bindgen` from the headers in `include/`. Do not edit.

use core::ffi::{c_char, c_int, c_void};
use core::marker::{PhantomData, PhantomPinned};

pub type Cronet_String = *const c_char;

pub type Cronet_RawDataPtr = *mut c_void;

pub type Cronet_ClientContext = *mut c_void;

/// Forward declare interfaces.
#[repr(C)]
pub struct Cronet_Buffer {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_BufferPtr = *mut Cronet_Buffer;

#[repr(C)]
pub struct Cronet_BufferCallback {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_BufferCallbackPtr = *mut Cronet_BufferCallback;

#[repr(C)]
pub struct Cronet_Runnable {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_RunnablePtr = *mut Cronet_Runnable;

#[repr(C)]
pub struct Cronet_Executor {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_ExecutorPtr = *mut Cronet_Executor;

#[repr(C)]
pub struct Cronet_Engine {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_EnginePtr = *mut Cronet_Engine;

#[repr(C)]
pub struct Cronet_UrlRequestStatusListener {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UrlRequestStatusListenerPtr = *mut Cronet_UrlRequestStatusListener;

#[repr(C)]
pub struct Cronet_UrlRequestCallback {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UrlRequestCallbackPtr = *mut Cronet_UrlRequestCallback;

#[repr(C)]
pub struct Cronet_UploadDataSink {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UploadDataSinkPtr = *mut Cronet_UploadDataSink;

#[repr(C)]
pub struct Cronet_UploadDataProvider {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UploadDataProviderPtr = *mut Cronet_UploadDataProvider;

#[repr(C)]
pub struct Cronet_UrlRequest {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UrlRequestPtr = *mut Cronet_UrlRequest;

#[repr(C)]
pub struct Cronet_RequestFinishedInfoListener {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_RequestFinishedInfoListenerPtr = *mut Cronet_RequestFinishedInfoListener;

/// Forward declare structs.
#[repr(C)]
pub struct Cronet_Error {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_ErrorPtr = *mut Cronet_Error;

#[repr(C)]
pub struct Cronet_QuicHint {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_QuicHintPtr = *mut Cronet_QuicHint;

#[repr(C)]
pub struct Cronet_PublicKeyPins {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_PublicKeyPinsPtr = *mut Cronet_PublicKeyPins;

#[repr(C)]
pub struct Cronet_EngineParams {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_EngineParamsPtr = *mut Cronet_EngineParams;

#[repr(C)]
pub struct Cronet_HttpHeader {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_HttpHeaderPtr = *mut Cronet_HttpHeader;

#[repr(C)]
pub struct Cronet_UrlResponseInfo {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UrlResponseInfoPtr = *mut Cronet_UrlResponseInfo;

#[repr(C)]
pub struct Cronet_UrlRequestParams {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_UrlRequestParamsPtr = *mut Cronet_UrlRequestParams;

#[repr(C)]
pub struct Cronet_DateTime {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_DateTimePtr = *mut Cronet_DateTime;

#[repr(C)]
pub struct Cronet_Metrics {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_MetricsPtr = *mut Cronet_Metrics;

#[repr(C)]
pub struct Cronet_RequestFinishedInfo {
    _data: [u8; 0],
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

pub type Cronet_RequestFinishedInfoPtr = *mut Cronet_RequestFinishedInfo;

/// Declare enums
pub type Cronet_RESULT = c_int;
pub const Cronet_RESULT_SUCCESS: Cronet_RESULT = 0;
pub const Cronet_RESULT_ILLEGAL_ARGUMENT: Cronet_RESULT = -100;
pub const Cronet_RESULT_ILLEGAL_ARGUMENT_STORAGE_PATH_MUST_EXIST: Cronet_RESULT = -101;
pub const Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_PIN: Cronet_RESULT = -102;
pub const Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_HOSTNAME: Cronet_RESULT = -103;
pub const Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_HTTP_METHOD: Cronet_RESULT = -104;
pub const Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_HTTP_HEADER: Cronet_RESULT = -105;
pub const Cronet_RESULT_ILLEGAL_STATE: Cronet_RESULT = -200;
pub const Cronet_RESULT_ILLEGAL_STATE_STORAGE_PATH_IN_USE: Cronet_RESULT = -201;
pub const Cronet_RESULT_ILLEGAL_STATE_CANNOT_SHUTDOWN_ENGINE_FROM_NETWORK_THREAD: Cronet_RESULT = -202;
pub const Cronet_RESULT_ILLEGAL_STATE_ENGINE_ALREADY_STARTED: Cronet_RESULT = -203;
pub const Cronet_RESULT_ILLEGAL_STATE_REQUEST_ALREADY_STARTED: Cronet_RESULT = -204;
pub const Cronet_RESULT_ILLEGAL_STATE_REQUEST_NOT_INITIALIZED: Cronet_RESULT = -205;
pub const Cronet_RESULT_ILLEGAL_STATE_REQUEST_ALREADY_INITIALIZED: Cronet_RESULT = -206;
pub const Cronet_RESULT_ILLEGAL_STATE_REQUEST_NOT_STARTED: Cronet_RESULT = -207;
pub const Cronet_RESULT_ILLEGAL_STATE_UNEXPECTED_REDIRECT: Cronet_RESULT = -208;
pub const Cronet_RESULT_ILLEGAL_STATE_UNEXPECTED_READ: Cronet_RESULT = -209;
pub const Cronet_RESULT_ILLEGAL_STATE_READ_FAILED: Cronet_RESULT = -210;
pub const Cronet_RESULT_NULL_POINTER: Cronet_RESULT = -300;
pub const Cronet_RESULT_NULL_POINTER_HOSTNAME: Cronet_RESULT = -301;
pub const Cronet_RESULT_NULL_POINTER_SHA256_PINS: Cronet_RESULT = -302;
pub const Cronet_RESULT_NULL_POINTER_EXPIRATION_DATE: Cronet_RESULT = -303;
pub const Cronet_RESULT_NULL_POINTER_ENGINE: Cronet_RESULT = -304;
pub const Cronet_RESULT_NULL_POINTER_URL: Cronet_RESULT = -305;
pub const Cronet_RESULT_NULL_POINTER_CALLBACK: Cronet_RESULT = -306;
pub const Cronet_RESULT_NULL_POINTER_EXECUTOR: Cronet_RESULT = -307;
pub const Cronet_RESULT_NULL_POINTER_METHOD: Cronet_RESULT = -308;
pub const Cronet_RESULT_NULL_POINTER_HEADER_NAME: Cronet_RESULT = -309;
pub const Cronet_RESULT_NULL_POINTER_HEADER_VALUE: Cronet_RESULT = -310;
pub const Cronet_RESULT_NULL_POINTER_PARAMS: Cronet_RESULT = -311;
pub const Cronet_RESULT_NULL_POINTER_REQUEST_FINISHED_INFO_LISTENER_EXECUTOR: Cronet_RESULT = -312;

pub type Cronet_Error_ERROR_CODE = c_int;
pub const Cronet_Error_ERROR_CODE_ERROR_CALLBACK: Cronet_Error_ERROR_CODE = 0;
pub const Cronet_Error_ERROR_CODE_ERROR_HOSTNAME_NOT_RESOLVED: Cronet_Error_ERROR_CODE = 1;
pub const Cronet_Error_ERROR_CODE_ERROR_INTERNET_DISCONNECTED: Cronet_Error_ERROR_CODE = 2;
pub const Cronet_Error_ERROR_CODE_ERROR_NETWORK_CHANGED: Cronet_Error_ERROR_CODE = 3;
pub const Cronet_Error_ERROR_CODE_ERROR_TIMED_OUT: Cronet_Error_ERROR_CODE = 4;
pub const Cronet_Error_ERROR_CODE_ERROR_CONNECTION_CLOSED: Cronet_Error_ERROR_CODE = 5;
pub const Cronet_Error_ERROR_CODE_ERROR_CONNECTION_TIMED_OUT: Cronet_Error_ERROR_CODE = 6;
pub const Cronet_Error_ERROR_CODE_ERROR_CONNECTION_REFUSED: Cronet_Error_ERROR_CODE = 7;
pub const Cronet_Error_ERROR_CODE_ERROR_CONNECTION_RESET: Cronet_Error_ERROR_CODE = 8;
pub const Cronet_Error_ERROR_CODE_ERROR_ADDRESS_UNREACHABLE: Cronet_Error_ERROR_CODE = 9;
pub const Cronet_Error_ERROR_CODE_ERROR_QUIC_PROTOCOL_FAILED: Cronet_Error_ERROR_CODE = 10;
pub const Cronet_Error_ERROR_CODE_ERROR_OTHER: Cronet_Error_ERROR_CODE = 11;

pub type Cronet_EngineParams_HTTP_CACHE_MODE = c_int;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_DISABLED: Cronet_EngineParams_HTTP_CACHE_MODE = 0;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_IN_MEMORY: Cronet_EngineParams_HTTP_CACHE_MODE = 1;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_DISK_NO_HTTP: Cronet_EngineParams_HTTP_CACHE_MODE = 2;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_DISK: Cronet_EngineParams_HTTP_CACHE_MODE = 3;

pub type Cronet_UrlRequestParams_REQUEST_PRIORITY = c_int;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_IDLE: Cronet_UrlRequestParams_REQUEST_PRIORITY = 0;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_LOWEST: Cronet_UrlRequestParams_REQUEST_PRIORITY =
    1;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_LOW: Cronet_UrlRequestParams_REQUEST_PRIORITY = 2;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_MEDIUM: Cronet_UrlRequestParams_REQUEST_PRIORITY =
    3;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_HIGHEST: Cronet_UrlRequestParams_REQUEST_PRIORITY =
    4;

pub type Cronet_UrlRequestParams_IDEMPOTENCY = c_int;
pub const Cronet_UrlRequestParams_IDEMPOTENCY_DEFAULT_IDEMPOTENCY: Cronet_UrlRequestParams_IDEMPOTENCY = 0;
pub const Cronet_UrlRequestParams_IDEMPOTENCY_IDEMPOTENT: Cronet_UrlRequestParams_IDEMPOTENCY = 1;
pub const Cronet_UrlRequestParams_IDEMPOTENCY_NOT_IDEMPOTENT: Cronet_UrlRequestParams_IDEMPOTENCY = 2;

pub type Cronet_RequestFinishedInfo_FINISHED_REASON = c_int;
pub const Cronet_RequestFinishedInfo_FINISHED_REASON_SUCCEEDED: Cronet_RequestFinishedInfo_FINISHED_REASON = 0;
pub const Cronet_RequestFinishedInfo_FINISHED_REASON_FAILED: Cronet_RequestFinishedInfo_FINISHED_REASON = 1;
pub const Cronet_RequestFinishedInfo_FINISHED_REASON_CANCELED: Cronet_RequestFinishedInfo_FINISHED_REASON = 2;

pub type Cronet_UrlRequestStatusListener_Status = c_int;
pub const Cronet_UrlRequestStatusListener_Status_INVALID: Cronet_UrlRequestStatusListener_Status = -1;
pub const Cronet_UrlRequestStatusListener_Status_IDLE: Cronet_UrlRequestStatusListener_Status = 0;
pub const Cronet_UrlRequestStatusListener_Status_WAITING_FOR_STALLED_SOCKET_POOL:
    Cronet_UrlRequestStatusListener_Status = 1;
pub const Cronet_UrlRequestStatusListener_Status_WAITING_FOR_AVAILABLE_SOCKET: Cronet_UrlRequestStatusListener_Status =
    2;
pub const Cronet_UrlRequestStatusListener_Status_WAITING_FOR_DELEGATE: Cronet_UrlRequestStatusListener_Status = 3;
pub const Cronet_UrlRequestStatusListener_Status_WAITING_FOR_CACHE: Cronet_UrlRequestStatusListener_Status = 4;
pub const Cronet_UrlRequestStatusListener_Status_DOWNLOADING_PAC_FILE: Cronet_UrlRequestStatusListener_Status = 5;
pub const Cronet_UrlRequestStatusListener_Status_RESOLVING_PROXY_FOR_URL: Cronet_UrlRequestStatusListener_Status = 6;
pub const Cronet_UrlRequestStatusListener_Status_RESOLVING_HOST_IN_PAC_FILE: Cronet_UrlRequestStatusListener_Status = 7;
pub const Cronet_UrlRequestStatusListener_Status_ESTABLISHING_PROXY_TUNNEL: Cronet_UrlRequestStatusListener_Status = 8;
pub const Cronet_UrlRequestStatusListener_Status_RESOLVING_HOST: Cronet_UrlRequestStatusListener_Status = 9;
pub const Cronet_UrlRequestStatusListener_Status_CONNECTING: Cronet_UrlRequestStatusListener_Status = 10;
pub const Cronet_UrlRequestStatusListener_Status_SSL_HANDSHAKE: Cronet_UrlRequestStatusListener_Status = 11;
pub const Cronet_UrlRequestStatusListener_Status_SENDING_REQUEST: Cronet_UrlRequestStatusListener_Status = 12;
pub const Cronet_UrlRequestStatusListener_Status_WAITING_FOR_RESPONSE: Cronet_UrlRequestStatusListener_Status = 13;
pub const Cronet_UrlRequestStatusListener_Status_READING_RESPONSE: Cronet_UrlRequestStatusListener_Status = 14;

/// Concrete interface Cronet_Buffer is implemented by Cronet.
/// The app can implement these for testing / mocking.
pub type Cronet_Buffer_InitWithDataAndCallbackFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_BufferPtr,
        data: Cronet_RawDataPtr,
        size: u64,
        callback: Cronet_BufferCallbackPtr,
    ),
>;

pub type Cronet_Buffer_InitWithAllocFunc = Option<unsafe extern "C" fn(self_: Cronet_BufferPtr, size: u64)>;

pub type Cronet_Buffer_GetSizeFunc = Option<unsafe extern "C" fn(self_: Cronet_BufferPtr) -> u64>;

pub type Cronet_Buffer_GetDataFunc = Option<unsafe extern "C" fn(self_: Cronet_BufferPtr) -> Cronet_RawDataPtr>;

/// The app implements abstract interface Cronet_BufferCallback by defining
/// custom functions for each method.
pub type Cronet_BufferCallback_OnDestroyFunc =
    Option<unsafe extern "C" fn(self_: Cronet_BufferCallbackPtr, buffer: Cronet_BufferPtr)>;

/// The app implements abstract interface Cronet_Runnable by defining custom
/// functions for each method.
pub type Cronet_Runnable_RunFunc = Option<unsafe extern "C" fn(self_: Cronet_RunnablePtr)>;

/// The app implements abstract interface Cronet_Executor by defining custom
/// functions for each method.
pub type Cronet_Executor_ExecuteFunc =
    Option<unsafe extern "C" fn(self_: Cronet_ExecutorPtr, command: Cronet_RunnablePtr)>;

/// Concrete interface Cronet_Engine is implemented by Cronet.
/// The app can implement these for testing / mocking.
pub type Cronet_Engine_StartWithParamsFunc =
    Option<unsafe extern "C" fn(self_: Cronet_EnginePtr, params: Cronet_EngineParamsPtr) -> Cronet_RESULT>;

pub type Cronet_Engine_StartNetLogToFileFunc =
    Option<unsafe extern "C" fn(self_: Cronet_EnginePtr, file_name: Cronet_String, log_all: bool) -> bool>;

pub type Cronet_Engine_StopNetLogFunc = Option<unsafe extern "C" fn(self_: Cronet_EnginePtr)>;

pub type Cronet_Engine_ShutdownFunc = Option<unsafe extern "C" fn(self_: Cronet_EnginePtr) -> Cronet_RESULT>;

pub type Cronet_Engine_GetVersionStringFunc = Option<unsafe extern "C" fn(self_: Cronet_EnginePtr) -> Cronet_String>;

pub type Cronet_Engine_GetDefaultUserAgentFunc = Option<unsafe extern "C" fn(self_: Cronet_EnginePtr) -> Cronet_String>;

pub type Cronet_Engine_AddRequestFinishedListenerFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_EnginePtr,
        listener: Cronet_RequestFinishedInfoListenerPtr,
        executor: Cronet_ExecutorPtr,
    ),
>;

pub type Cronet_Engine_RemoveRequestFinishedListenerFunc =
    Option<unsafe extern "C" fn(self_: Cronet_EnginePtr, listener: Cronet_RequestFinishedInfoListenerPtr)>;

/// The app implements abstract interface Cronet_UrlRequestStatusListener by
/// defining custom functions for each method.
pub type Cronet_UrlRequestStatusListener_OnStatusFunc = Option<
    unsafe extern "C" fn(self_: Cronet_UrlRequestStatusListenerPtr, status: Cronet_UrlRequestStatusListener_Status),
>;

/// The app implements abstract interface Cronet_UrlRequestCallback by defining
/// custom functions for each method.
pub type Cronet_UrlRequestCallback_OnRedirectReceivedFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        new_location_url: Cronet_String,
    ),
>;

pub type Cronet_UrlRequestCallback_OnResponseStartedFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    ),
>;

pub type Cronet_UrlRequestCallback_OnReadCompletedFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        buffer: Cronet_BufferPtr,
        bytes_read: u64,
    ),
>;

pub type Cronet_UrlRequestCallback_OnSucceededFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    ),
>;

pub type Cronet_UrlRequestCallback_OnFailedFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    ),
>;

pub type Cronet_UrlRequestCallback_OnCanceledFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    ),
>;

/// Concrete interface Cronet_UploadDataSink is implemented by Cronet.
/// The app can implement these for testing / mocking.
pub type Cronet_UploadDataSink_OnReadSucceededFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr, bytes_read: u64, final_chunk: bool)>;

pub type Cronet_UploadDataSink_OnReadErrorFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr, error_message: Cronet_String)>;

pub type Cronet_UploadDataSink_OnRewindSucceededFunc = Option<unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr)>;

pub type Cronet_UploadDataSink_OnRewindErrorFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr, error_message: Cronet_String)>;

/// The app implements abstract interface Cronet_UploadDataProvider by defining
/// custom functions for each method.
pub type Cronet_UploadDataProvider_GetLengthFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UploadDataProviderPtr) -> i64>;

pub type Cronet_UploadDataProvider_ReadFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
        buffer: Cronet_BufferPtr,
    ),
>;

pub type Cronet_UploadDataProvider_RewindFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UploadDataProviderPtr, upload_data_sink: Cronet_UploadDataSinkPtr)>;

pub type Cronet_UploadDataProvider_CloseFunc = Option<unsafe extern "C" fn(self_: Cronet_UploadDataProviderPtr)>;

/// Concrete interface Cronet_UrlRequest is implemented by Cronet.
/// The app can implement these for testing / mocking.
pub type Cronet_UrlRequest_InitWithParamsFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestPtr,
        engine: Cronet_EnginePtr,
        url: Cronet_String,
        params: Cronet_UrlRequestParamsPtr,
        callback: Cronet_UrlRequestCallbackPtr,
        executor: Cronet_ExecutorPtr,
    ) -> Cronet_RESULT,
>;

pub type Cronet_UrlRequest_StartFunc = Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT>;

pub type Cronet_UrlRequest_FollowRedirectFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT>;

pub type Cronet_UrlRequest_ReadFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr, buffer: Cronet_BufferPtr) -> Cronet_RESULT>;

pub type Cronet_UrlRequest_CancelFunc = Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr)>;

pub type Cronet_UrlRequest_IsDoneFunc = Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr) -> bool>;

pub type Cronet_UrlRequest_GetStatusFunc =
    Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr, listener: Cronet_UrlRequestStatusListenerPtr)>;

/// The app implements abstract interface Cronet_RequestFinishedInfoListener by
/// defining custom functions for each method.
pub type Cronet_RequestFinishedInfoListener_OnRequestFinishedFunc = Option<
    unsafe extern "C" fn(
        self_: Cronet_RequestFinishedInfoListenerPtr,
        request_info: Cronet_RequestFinishedInfoPtr,
        response_info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    ),
>;

/// Dialer callback type for custom TCP connection establishment.
/// context: User-provided context pointer passed to Cronet_Engine_SetDialer.
/// address: IP address string (e.g. "1.2.3.4" or "::1").
/// port: Port number.
/// Returns: connected socket fd on success, negative net error code on failure.
/// Common error codes:
/// -102: ERR_CONNECTION_REFUSED
/// -104: ERR_CONNECTION_FAILED
/// -109: ERR_ADDRESS_UNREACHABLE
/// -118: ERR_CONNECTION_TIMED_OUT
pub type Cronet_DialerFunc =
    Option<unsafe extern "C" fn(context: *mut c_void, address: *const c_char, port: u16) -> isize>;

/// UDP Dialer callback type for custom UDP socket creation.
/// context: User-provided context pointer passed to Cronet_Engine_SetUdpDialer.
/// address: IP address string (e.g. "1.2.3.4" or "::1").
/// port: Port number.
/// out_local_address: Output buffer for local IP address (caller provides
/// buffer,
/// should be at least 46 bytes for INET6_ADDRSTRLEN).
/// out_local_port: Output pointer for local port number.
/// out_socket_id: Opaque identifier passed to on_close; zero skips notification.
/// Returns: socket fd on success, negative net error code on failure.
/// The returned socket can be:
/// - AF_INET/AF_INET6 SOCK_DGRAM: Standard UDP socket
/// - AF_UNIX SOCK_DGRAM: Unix domain datagram socket (Unix/macOS/Linux)
/// - AF_UNIX SOCK_STREAM: Unix domain stream socket (Windows, with framing)
pub type Cronet_UdpDialerFunc = Option<
    unsafe extern "C" fn(
        context: *mut c_void,
        address: *const c_char,
        port: u16,
        out_local_address: *mut c_char,
        out_local_port: *mut u16,
        out_socket_id: *mut u64,
    ) -> isize,
>;

pub type Cronet_UdpSocketCloseFunc = Option<unsafe extern "C" fn(socket_id: u64)>;

/// Opaque object representing a Bidirectional stream creating engine. Created
/// and configured outside of this API to facilitate sharing with other
/// components
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct stream_engine {
    pub obj: *mut c_void,
    pub annotation: *mut c_void,
}

/// Opaque object representing Bidirectional Stream.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct bidirectional_stream {
    pub obj: *mut c_void,
    pub annotation: *mut c_void,
}

/// A single request or response header element.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct bidirectional_stream_header {
    pub key: *const c_char,
    pub value: *const c_char,
}

/// Array of request or response headers or trailers.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct bidirectional_stream_header_array {
    pub count: usize,
    pub capacity: usize,
    pub headers: *mut bidirectional_stream_header,
}

/// Set of callbacks used to receive callbacks from bidirectional stream.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct bidirectional_stream_callback {
    /// Invoked when the stream is ready for reading and writing. * Consumer may call bidirectional_stream_read() to start reading data. * Consumer may call bidirectional_stream_write() to start writing * data.
    pub on_stream_ready: Option<unsafe extern "C" fn(stream: *mut bidirectional_stream)>,
    /// Invoked when initial response headers are received. * Consumer must call bidirectional_stream_read() to start reading. * Consumer may call bidirectional_stream_write() to start writing or * close the stream. Contents of |headers| is valid for duration of the call.
    pub on_response_headers_received: Option<
        unsafe extern "C" fn(
            stream: *mut bidirectional_stream,
            headers: *const bidirectional_stream_header_array,
            negotiated_protocol: *const c_char,
        ),
    >,
    /// Invoked when data is read into the buffer passed to * bidirectional_stream_read(). Only part of the buffer may be * populated. To continue reading, call bidirectional_stream_read(). * It may be invoked after on_response_trailers_received()}, if there was * pending read data before trailers were received. * * If |bytes_read| is 0, it means the remote side has signaled that it will * send no more data; future calls to bidirectional_stream_read() * will result in the on_data_read() callback or on_succeded() callback if * bidirectional_stream_write() was invoked with end_of_stream set to * true.
    pub on_read_completed:
        Option<unsafe extern "C" fn(stream: *mut bidirectional_stream, data: *mut c_char, bytes_read: c_int)>,
    /// * Invoked when all data passed to bidirectional_stream_write() is * sent. To continue writing, call bidirectional_stream_write().
    pub on_write_completed: Option<unsafe extern "C" fn(stream: *mut bidirectional_stream, data: *const c_char)>,
    /// Invoked when trailers are received before closing the stream. Only invoked * when server sends trailers, which it may not. May be invoked while there is * read data remaining in local buffer. Contents of |trailers| is valid for * duration of the call.
    pub on_response_trailers_received: Option<
        unsafe extern "C" fn(stream: *mut bidirectional_stream, trailers: *const bidirectional_stream_header_array),
    >,
    /// * Invoked when there is no data to be read or written and the stream is * closed successfully remotely and locally. Once invoked, no further callback * methods will be invoked.
    pub on_succeded: Option<unsafe extern "C" fn(stream: *mut bidirectional_stream)>,
    /// * Invoked if the stream failed for any reason after * bidirectional_stream_start(). HTTP/2 error codes are * mapped to chrome net error codes. Once invoked, no further callback methods * will be invoked.
    pub on_failed: Option<unsafe extern "C" fn(stream: *mut bidirectional_stream, net_error: c_int)>,
    /// * Invoked if the stream was canceled via * bidirectional_stream_cancel(). Once invoked, no further callback * methods will be invoked.
    pub on_canceled: Option<unsafe extern "C" fn(stream: *mut bidirectional_stream)>,
}

cronet_api! {
    /// Create an instance of Cronet_Buffer.
    pub fn Cronet_Buffer_Create() -> Cronet_BufferPtr;
    /// Destroy an instance of Cronet_Buffer.
    pub fn Cronet_Buffer_Destroy(self_: Cronet_BufferPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_Buffer_SetClientContext(self_: Cronet_BufferPtr, client_context: Cronet_ClientContext);
    pub fn Cronet_Buffer_GetClientContext(self_: Cronet_BufferPtr) -> Cronet_ClientContext;
    /// Concrete methods of Cronet_Buffer implemented by Cronet.
    /// The app calls them to manipulate Cronet_Buffer.
    pub fn Cronet_Buffer_InitWithDataAndCallback(
        self_: Cronet_BufferPtr,
        data: Cronet_RawDataPtr,
        size: u64,
        callback: Cronet_BufferCallbackPtr,
    );
    pub fn Cronet_Buffer_InitWithAlloc(self_: Cronet_BufferPtr, size: u64);
    pub fn Cronet_Buffer_GetSize(self_: Cronet_BufferPtr) -> u64;
    pub fn Cronet_Buffer_GetData(self_: Cronet_BufferPtr) -> Cronet_RawDataPtr;
    /// Concrete interface Cronet_Buffer is implemented by Cronet.
    /// The app can use this for testing / mocking.
    pub fn Cronet_Buffer_CreateWith(
        InitWithDataAndCallbackFunc: Cronet_Buffer_InitWithDataAndCallbackFunc,
        InitWithAllocFunc: Cronet_Buffer_InitWithAllocFunc,
        GetSizeFunc: Cronet_Buffer_GetSizeFunc,
        GetDataFunc: Cronet_Buffer_GetDataFunc,
    ) -> Cronet_BufferPtr;
    /// Destroy an instance of Cronet_BufferCallback.
    pub fn Cronet_BufferCallback_Destroy(self_: Cronet_BufferCallbackPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_BufferCallback_SetClientContext(
        self_: Cronet_BufferCallbackPtr,
        client_context: Cronet_ClientContext,
    );
    pub fn Cronet_BufferCallback_GetClientContext(self_: Cronet_BufferCallbackPtr) -> Cronet_ClientContext;
    /// Abstract interface Cronet_BufferCallback is implemented by the app.
    /// The following concrete methods forward call to app implementation.
    /// The app doesn't normally call them.
    pub fn Cronet_BufferCallback_OnDestroy(self_: Cronet_BufferCallbackPtr, buffer: Cronet_BufferPtr);
    /// The app creates an instance of Cronet_BufferCallback by providing custom
    /// functions for each method.
    pub fn Cronet_BufferCallback_CreateWith(
        OnDestroyFunc: Cronet_BufferCallback_OnDestroyFunc,
    ) -> Cronet_BufferCallbackPtr;
    /// Destroy an instance of Cronet_Runnable.
    pub fn Cronet_Runnable_Destroy(self_: Cronet_RunnablePtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_Runnable_SetClientContext(self_: Cronet_RunnablePtr, client_context: Cronet_ClientContext);
    pub fn Cronet_Runnable_GetClientContext(self_: Cronet_RunnablePtr) -> Cronet_ClientContext;
    /// Abstract interface Cronet_Runnable is implemented by the app.
    /// The following concrete methods forward call to app implementation.
    /// The app doesn't normally call them.
    pub fn Cronet_Runnable_Run(self_: Cronet_RunnablePtr);
    /// The app creates an instance of Cronet_Runnable by providing custom functions
    /// for each method.
    pub fn Cronet_Runnable_CreateWith(RunFunc: Cronet_Runnable_RunFunc) -> Cronet_RunnablePtr;
    /// Destroy an instance of Cronet_Executor.
    pub fn Cronet_Executor_Destroy(self_: Cronet_ExecutorPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_Executor_SetClientContext(self_: Cronet_ExecutorPtr, client_context: Cronet_ClientContext);
    pub fn Cronet_Executor_GetClientContext(self_: Cronet_ExecutorPtr) -> Cronet_ClientContext;
    /// Abstract interface Cronet_Executor is implemented by the app.
    /// The following concrete methods forward call to app implementation.
    /// The app doesn't normally call them.
    pub fn Cronet_Executor_Execute(self_: Cronet_ExecutorPtr, command: Cronet_RunnablePtr);
    /// The app creates an instance of Cronet_Executor by providing custom functions
    /// for each method.
    pub fn Cronet_Executor_CreateWith(ExecuteFunc: Cronet_Executor_ExecuteFunc) -> Cronet_ExecutorPtr;
    /// Create an instance of Cronet_Engine.
    pub fn Cronet_Engine_Create() -> Cronet_EnginePtr;
    /// Destroy an instance of Cronet_Engine.
    pub fn Cronet_Engine_Destroy(self_: Cronet_EnginePtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_Engine_SetClientContext(self_: Cronet_EnginePtr, client_context: Cronet_ClientContext);
    pub fn Cronet_Engine_GetClientContext(self_: Cronet_EnginePtr) -> Cronet_ClientContext;
    /// Concrete methods of Cronet_Engine implemented by Cronet.
    /// The app calls them to manipulate Cronet_Engine.
    pub fn Cronet_Engine_StartWithParams(self_: Cronet_EnginePtr, params: Cronet_EngineParamsPtr) -> Cronet_RESULT;
    pub fn Cronet_Engine_StartNetLogToFile(self_: Cronet_EnginePtr, file_name: Cronet_String, log_all: bool) -> bool;
    pub fn Cronet_Engine_StopNetLog(self_: Cronet_EnginePtr);
    pub fn Cronet_Engine_Shutdown(self_: Cronet_EnginePtr) -> Cronet_RESULT;
    pub fn Cronet_Engine_GetVersionString(self_: Cronet_EnginePtr) -> Cronet_String;
    pub fn Cronet_Engine_GetDefaultUserAgent(self_: Cronet_EnginePtr) -> Cronet_String;
    pub fn Cronet_Engine_AddRequestFinishedListener(
        self_: Cronet_EnginePtr,
        listener: Cronet_RequestFinishedInfoListenerPtr,
        executor: Cronet_ExecutorPtr,
    );
    pub fn Cronet_Engine_RemoveRequestFinishedListener(
        self_: Cronet_EnginePtr,
        listener: Cronet_RequestFinishedInfoListenerPtr,
    );
    /// Concrete interface Cronet_Engine is implemented by Cronet.
    /// The app can use this for testing / mocking.
    pub fn Cronet_Engine_CreateWith(
        StartWithParamsFunc: Cronet_Engine_StartWithParamsFunc,
        StartNetLogToFileFunc: Cronet_Engine_StartNetLogToFileFunc,
        StopNetLogFunc: Cronet_Engine_StopNetLogFunc,
        ShutdownFunc: Cronet_Engine_ShutdownFunc,
        GetVersionStringFunc: Cronet_Engine_GetVersionStringFunc,
        GetDefaultUserAgentFunc: Cronet_Engine_GetDefaultUserAgentFunc,
        AddRequestFinishedListenerFunc: Cronet_Engine_AddRequestFinishedListenerFunc,
        RemoveRequestFinishedListenerFunc: Cronet_Engine_RemoveRequestFinishedListenerFunc,
    ) -> Cronet_EnginePtr;
    /// Destroy an instance of Cronet_UrlRequestStatusListener.
    pub fn Cronet_UrlRequestStatusListener_Destroy(self_: Cronet_UrlRequestStatusListenerPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_UrlRequestStatusListener_SetClientContext(
        self_: Cronet_UrlRequestStatusListenerPtr,
        client_context: Cronet_ClientContext,
    );
    pub fn Cronet_UrlRequestStatusListener_GetClientContext(
        self_: Cronet_UrlRequestStatusListenerPtr,
    ) -> Cronet_ClientContext;
    /// Abstract interface Cronet_UrlRequestStatusListener is implemented by the app.
    /// The following concrete methods forward call to app implementation.
    /// The app doesn't normally call them.
    pub fn Cronet_UrlRequestStatusListener_OnStatus(
        self_: Cronet_UrlRequestStatusListenerPtr,
        status: Cronet_UrlRequestStatusListener_Status,
    );
    /// The app creates an instance of Cronet_UrlRequestStatusListener by providing
    /// custom functions for each method.
    pub fn Cronet_UrlRequestStatusListener_CreateWith(
        OnStatusFunc: Cronet_UrlRequestStatusListener_OnStatusFunc,
    ) -> Cronet_UrlRequestStatusListenerPtr;
    /// Destroy an instance of Cronet_UrlRequestCallback.
    pub fn Cronet_UrlRequestCallback_Destroy(self_: Cronet_UrlRequestCallbackPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_UrlRequestCallback_SetClientContext(
        self_: Cronet_UrlRequestCallbackPtr,
        client_context: Cronet_ClientContext,
    );
    pub fn Cronet_UrlRequestCallback_GetClientContext(self_: Cronet_UrlRequestCallbackPtr) -> Cronet_ClientContext;
    /// Abstract interface Cronet_UrlRequestCallback is implemented by the app.
    /// The following concrete methods forward call to app implementation.
    /// The app doesn't normally call them.
    pub fn Cronet_UrlRequestCallback_OnRedirectReceived(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        new_location_url: Cronet_String,
    );
    pub fn Cronet_UrlRequestCallback_OnResponseStarted(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    );
    pub fn Cronet_UrlRequestCallback_OnReadCompleted(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        buffer: Cronet_BufferPtr,
        bytes_read: u64,
    );
    pub fn Cronet_UrlRequestCallback_OnSucceeded(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    );
    pub fn Cronet_UrlRequestCallback_OnFailed(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    );
    pub fn Cronet_UrlRequestCallback_OnCanceled(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    );
    /// The app creates an instance of Cronet_UrlRequestCallback by providing custom
    /// functions for each method.
    pub fn Cronet_UrlRequestCallback_CreateWith(
        OnRedirectReceivedFunc: Cronet_UrlRequestCallback_OnRedirectReceivedFunc,
        OnResponseStartedFunc: Cronet_UrlRequestCallback_OnResponseStartedFunc,
        OnReadCompletedFunc: Cronet_UrlRequestCallback_OnReadCompletedFunc,
        OnSucceededFunc: Cronet_UrlRequestCallback_OnSucceededFunc,
        OnFailedFunc: Cronet_UrlRequestCallback_OnFailedFunc,
        OnCanceledFunc: Cronet_UrlRequestCallback_OnCanceledFunc,
    ) -> Cronet_UrlRequestCallbackPtr;
    /// Destroy an instance of Cronet_UploadDataSink.
    pub fn Cronet_UploadDataSink_Destroy(self_: Cronet_UploadDataSinkPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_UploadDataSink_SetClientContext(
        self_: Cronet_UploadDataSinkPtr,
        client_context: Cronet_ClientContext,
    );
    pub fn Cronet_UploadDataSink_GetClientContext(self_: Cronet_UploadDataSinkPtr) -> Cronet_ClientContext;
    /// Concrete methods of Cronet_UploadDataSink implemented by Cronet.
    /// The app calls them to manipulate Cronet_UploadDataSink.
    pub fn Cronet_UploadDataSink_OnReadSucceeded(self_: Cronet_UploadDataSinkPtr, bytes_read: u64, final_chunk: bool);
    pub fn Cronet_UploadDataSink_OnReadError(self_: Cronet_UploadDataSinkPtr, error_message: Cronet_String);
    pub fn Cronet_UploadDataSink_OnRewindSucceeded(self_: Cronet_UploadDataSinkPtr);
    pub fn Cronet_UploadDataSink_OnRewindError(self_: Cronet_UploadDataSinkPtr, error_message: Cronet_String);
    /// Concrete interface Cronet_UploadDataSink is implemented by Cronet.
    /// The app can use this for testing / mocking.
    pub fn Cronet_UploadDataSink_CreateWith(
        OnReadSucceededFunc: Cronet_UploadDataSink_OnReadSucceededFunc,
        OnReadErrorFunc: Cronet_UploadDataSink_OnReadErrorFunc,
        OnRewindSucceededFunc: Cronet_UploadDataSink_OnRewindSucceededFunc,
        OnRewindErrorFunc: Cronet_UploadDataSink_OnRewindErrorFunc,
    ) -> Cronet_UploadDataSinkPtr;
    /// Destroy an instance of Cronet_UploadDataProvider.
    pub fn Cronet_UploadDataProvider_Destroy(self_: Cronet_UploadDataProviderPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_UploadDataProvider_SetClientContext(
        self_: Cronet_UploadDataProviderPtr,
        client_context: Cronet_ClientContext,
    );
    pub fn Cronet_UploadDataProvider_GetClientContext(self_: Cronet_UploadDataProviderPtr) -> Cronet_ClientContext;
    /// Abstract interface Cronet_UploadDataProvider is implemented by the app.
    /// The following concrete methods forward call to app implementation.
    /// The app doesn't normally call them.
    pub fn Cronet_UploadDataProvider_GetLength(self_: Cronet_UploadDataProviderPtr) -> i64;
    pub fn Cronet_UploadDataProvider_Read(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
        buffer: Cronet_BufferPtr,
    );
    pub fn Cronet_UploadDataProvider_Rewind(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
    );
    pub fn Cronet_UploadDataProvider_Close(self_: Cronet_UploadDataProviderPtr);
    /// The app creates an instance of Cronet_UploadDataProvider by providing custom
    /// functions for each method.
    pub fn Cronet_UploadDataProvider_CreateWith(
        GetLengthFunc: Cronet_UploadDataProvider_GetLengthFunc,
        ReadFunc: Cronet_UploadDataProvider_ReadFunc,
        RewindFunc: Cronet_UploadDataProvider_RewindFunc,
        CloseFunc: Cronet_UploadDataProvider_CloseFunc,
    ) -> Cronet_UploadDataProviderPtr;
    /// Create an instance of Cronet_UrlRequest.
    pub fn Cronet_UrlRequest_Create() -> Cronet_UrlRequestPtr;
    /// Destroy an instance of Cronet_UrlRequest.
    pub fn Cronet_UrlRequest_Destroy(self_: Cronet_UrlRequestPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_UrlRequest_SetClientContext(self_: Cronet_UrlRequestPtr, client_context: Cronet_ClientContext);
    pub fn Cronet_UrlRequest_GetClientContext(self_: Cronet_UrlRequestPtr) -> Cronet_ClientContext;
    /// Concrete methods of Cronet_UrlRequest implemented by Cronet.
    /// The app calls them to manipulate Cronet_UrlRequest.
    pub fn Cronet_UrlRequest_InitWithParams(
        self_: Cronet_UrlRequestPtr,
        engine: Cronet_EnginePtr,
        url: Cronet_String,
        params: Cronet_UrlRequestParamsPtr,
        callback: Cronet_UrlRequestCallbackPtr,
        executor: Cronet_ExecutorPtr,
    ) -> Cronet_RESULT;
    pub fn Cronet_UrlRequest_Start(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT;
    pub fn Cronet_UrlRequest_FollowRedirect(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT;
    pub fn Cronet_UrlRequest_Read(self_: Cronet_UrlRequestPtr, buffer: Cronet_BufferPtr) -> Cronet_RESULT;
    pub fn Cronet_UrlRequest_Cancel(self_: Cronet_UrlRequestPtr);
    pub fn Cronet_UrlRequest_IsDone(self_: Cronet_UrlRequestPtr) -> bool;
    pub fn Cronet_UrlRequest_GetStatus(self_: Cronet_UrlRequestPtr, listener: Cronet_UrlRequestStatusListenerPtr);
    /// Concrete interface Cronet_UrlRequest is implemented by Cronet.
    /// The app can use this for testing / mocking.
    pub fn Cronet_UrlRequest_CreateWith(
        InitWithParamsFunc: Cronet_UrlRequest_InitWithParamsFunc,
        StartFunc: Cronet_UrlRequest_StartFunc,
        FollowRedirectFunc: Cronet_UrlRequest_FollowRedirectFunc,
        ReadFunc: Cronet_UrlRequest_ReadFunc,
        CancelFunc: Cronet_UrlRequest_CancelFunc,
        IsDoneFunc: Cronet_UrlRequest_IsDoneFunc,
        GetStatusFunc: Cronet_UrlRequest_GetStatusFunc,
    ) -> Cronet_UrlRequestPtr;
    /// Destroy an instance of Cronet_RequestFinishedInfoListener.
    pub fn Cronet_RequestFinishedInfoListener_Destroy(self_: Cronet_RequestFinishedInfoListenerPtr);
    /// Set and get app-specific Cronet_ClientContext.
    pub fn Cronet_RequestFinishedInfoListener_SetClientContext(
        self_: Cronet_RequestFinishedInfoListenerPtr,
        client_context: Cronet_ClientContext,
    );
    pub fn Cronet_RequestFinishedInfoListener_GetClientContext(
        self_: Cronet_RequestFinishedInfoListenerPtr,
    ) -> Cronet_ClientContext;
    /// Abstract interface Cronet_RequestFinishedInfoListener is implemented by the
    /// app. The following concrete methods forward call to app implementation. The
    /// app doesn't normally call them.
    pub fn Cronet_RequestFinishedInfoListener_OnRequestFinished(
        self_: Cronet_RequestFinishedInfoListenerPtr,
        request_info: Cronet_RequestFinishedInfoPtr,
        response_info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    );
    /// The app creates an instance of Cronet_RequestFinishedInfoListener by
    /// providing custom functions for each method.
    pub fn Cronet_RequestFinishedInfoListener_CreateWith(
        OnRequestFinishedFunc: Cronet_RequestFinishedInfoListener_OnRequestFinishedFunc,
    ) -> Cronet_RequestFinishedInfoListenerPtr;
    /// Struct Cronet_Error.
    pub fn Cronet_Error_Create() -> Cronet_ErrorPtr;
    pub fn Cronet_Error_Destroy(self_: Cronet_ErrorPtr);
    /// Cronet_Error setters.
    pub fn Cronet_Error_error_code_set(self_: Cronet_ErrorPtr, error_code: Cronet_Error_ERROR_CODE);
    pub fn Cronet_Error_message_set(self_: Cronet_ErrorPtr, message: Cronet_String);
    pub fn Cronet_Error_internal_error_code_set(self_: Cronet_ErrorPtr, internal_error_code: i32);
    pub fn Cronet_Error_immediately_retryable_set(self_: Cronet_ErrorPtr, immediately_retryable: bool);
    pub fn Cronet_Error_quic_detailed_error_code_set(self_: Cronet_ErrorPtr, quic_detailed_error_code: i32);
    /// Cronet_Error getters.
    pub fn Cronet_Error_error_code_get(self_: Cronet_ErrorPtr) -> Cronet_Error_ERROR_CODE;
    pub fn Cronet_Error_message_get(self_: Cronet_ErrorPtr) -> Cronet_String;
    pub fn Cronet_Error_internal_error_code_get(self_: Cronet_ErrorPtr) -> i32;
    pub fn Cronet_Error_immediately_retryable_get(self_: Cronet_ErrorPtr) -> bool;
    pub fn Cronet_Error_quic_detailed_error_code_get(self_: Cronet_ErrorPtr) -> i32;
    /// Struct Cronet_QuicHint.
    pub fn Cronet_QuicHint_Create() -> Cronet_QuicHintPtr;
    pub fn Cronet_QuicHint_Destroy(self_: Cronet_QuicHintPtr);
    /// Cronet_QuicHint setters.
    pub fn Cronet_QuicHint_host_set(self_: Cronet_QuicHintPtr, host: Cronet_String);
    pub fn Cronet_QuicHint_port_set(self_: Cronet_QuicHintPtr, port: i32);
    pub fn Cronet_QuicHint_alternate_port_set(self_: Cronet_QuicHintPtr, alternate_port: i32);
    /// Cronet_QuicHint getters.
    pub fn Cronet_QuicHint_host_get(self_: Cronet_QuicHintPtr) -> Cronet_String;
    pub fn Cronet_QuicHint_port_get(self_: Cronet_QuicHintPtr) -> i32;
    pub fn Cronet_QuicHint_alternate_port_get(self_: Cronet_QuicHintPtr) -> i32;
    /// Struct Cronet_PublicKeyPins.
    pub fn Cronet_PublicKeyPins_Create() -> Cronet_PublicKeyPinsPtr;
    pub fn Cronet_PublicKeyPins_Destroy(self_: Cronet_PublicKeyPinsPtr);
    /// Cronet_PublicKeyPins setters.
    pub fn Cronet_PublicKeyPins_host_set(self_: Cronet_PublicKeyPinsPtr, host: Cronet_String);
    pub fn Cronet_PublicKeyPins_pins_sha256_add(self_: Cronet_PublicKeyPinsPtr, element: Cronet_String);
    pub fn Cronet_PublicKeyPins_include_subdomains_set(self_: Cronet_PublicKeyPinsPtr, include_subdomains: bool);
    pub fn Cronet_PublicKeyPins_expiration_date_set(self_: Cronet_PublicKeyPinsPtr, expiration_date: i64);
    /// Cronet_PublicKeyPins getters.
    pub fn Cronet_PublicKeyPins_host_get(self_: Cronet_PublicKeyPinsPtr) -> Cronet_String;
    pub fn Cronet_PublicKeyPins_pins_sha256_size(self_: Cronet_PublicKeyPinsPtr) -> u32;
    pub fn Cronet_PublicKeyPins_pins_sha256_at(self_: Cronet_PublicKeyPinsPtr, index: u32) -> Cronet_String;
    pub fn Cronet_PublicKeyPins_pins_sha256_clear(self_: Cronet_PublicKeyPinsPtr);
    pub fn Cronet_PublicKeyPins_include_subdomains_get(self_: Cronet_PublicKeyPinsPtr) -> bool;
    pub fn Cronet_PublicKeyPins_expiration_date_get(self_: Cronet_PublicKeyPinsPtr) -> i64;
    /// Struct Cronet_EngineParams.
    pub fn Cronet_EngineParams_Create() -> Cronet_EngineParamsPtr;
    pub fn Cronet_EngineParams_Destroy(self_: Cronet_EngineParamsPtr);
    /// Cronet_EngineParams setters.
    pub fn Cronet_EngineParams_enable_check_result_set(self_: Cronet_EngineParamsPtr, enable_check_result: bool);
    pub fn Cronet_EngineParams_user_agent_set(self_: Cronet_EngineParamsPtr, user_agent: Cronet_String);
    pub fn Cronet_EngineParams_accept_language_set(self_: Cronet_EngineParamsPtr, accept_language: Cronet_String);
    pub fn Cronet_EngineParams_storage_path_set(self_: Cronet_EngineParamsPtr, storage_path: Cronet_String);
    pub fn Cronet_EngineParams_enable_quic_set(self_: Cronet_EngineParamsPtr, enable_quic: bool);
    pub fn Cronet_EngineParams_enable_http2_set(self_: Cronet_EngineParamsPtr, enable_http2: bool);
    pub fn Cronet_EngineParams_enable_brotli_set(self_: Cronet_EngineParamsPtr, enable_brotli: bool);
    pub fn Cronet_EngineParams_http_cache_mode_set(
        self_: Cronet_EngineParamsPtr,
        http_cache_mode: Cronet_EngineParams_HTTP_CACHE_MODE,
    );
    pub fn Cronet_EngineParams_http_cache_max_size_set(self_: Cronet_EngineParamsPtr, http_cache_max_size: i64);
    pub fn Cronet_EngineParams_quic_hints_add(self_: Cronet_EngineParamsPtr, element: Cronet_QuicHintPtr);
    pub fn Cronet_EngineParams_public_key_pins_add(self_: Cronet_EngineParamsPtr, element: Cronet_PublicKeyPinsPtr);
    pub fn Cronet_EngineParams_enable_public_key_pinning_bypass_for_local_trust_anchors_set(
        self_: Cronet_EngineParamsPtr,
        enable_public_key_pinning_bypass_for_local_trust_anchors: bool,
    );
    pub fn Cronet_EngineParams_network_thread_priority_set(self_: Cronet_EngineParamsPtr, network_thread_priority: f64);
    pub fn Cronet_EngineParams_experimental_options_set(
        self_: Cronet_EngineParamsPtr,
        experimental_options: Cronet_String,
    );
    /// Cronet_EngineParams getters.
    pub fn Cronet_EngineParams_enable_check_result_get(self_: Cronet_EngineParamsPtr) -> bool;
    pub fn Cronet_EngineParams_user_agent_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
    pub fn Cronet_EngineParams_accept_language_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
    pub fn Cronet_EngineParams_storage_path_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
    pub fn Cronet_EngineParams_enable_quic_get(self_: Cronet_EngineParamsPtr) -> bool;
    pub fn Cronet_EngineParams_enable_http2_get(self_: Cronet_EngineParamsPtr) -> bool;
    pub fn Cronet_EngineParams_enable_brotli_get(self_: Cronet_EngineParamsPtr) -> bool;
    pub fn Cronet_EngineParams_http_cache_mode_get(
        self_: Cronet_EngineParamsPtr,
    ) -> Cronet_EngineParams_HTTP_CACHE_MODE;
    pub fn Cronet_EngineParams_http_cache_max_size_get(self_: Cronet_EngineParamsPtr) -> i64;
    pub fn Cronet_EngineParams_quic_hints_size(self_: Cronet_EngineParamsPtr) -> u32;
    pub fn Cronet_EngineParams_quic_hints_at(self_: Cronet_EngineParamsPtr, index: u32) -> Cronet_QuicHintPtr;
    pub fn Cronet_EngineParams_quic_hints_clear(self_: Cronet_EngineParamsPtr);
    pub fn Cronet_EngineParams_public_key_pins_size(self_: Cronet_EngineParamsPtr) -> u32;
    pub fn Cronet_EngineParams_public_key_pins_at(self_: Cronet_EngineParamsPtr, index: u32) -> Cronet_PublicKeyPinsPtr;
    pub fn Cronet_EngineParams_public_key_pins_clear(self_: Cronet_EngineParamsPtr);
    pub fn Cronet_EngineParams_enable_public_key_pinning_bypass_for_local_trust_anchors_get(
        self_: Cronet_EngineParamsPtr,
    ) -> bool;
    pub fn Cronet_EngineParams_network_thread_priority_get(self_: Cronet_EngineParamsPtr) -> f64;
    pub fn Cronet_EngineParams_experimental_options_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
    /// Struct Cronet_HttpHeader.
    pub fn Cronet_HttpHeader_Create() -> Cronet_HttpHeaderPtr;
    pub fn Cronet_HttpHeader_Destroy(self_: Cronet_HttpHeaderPtr);
    /// Cronet_HttpHeader setters.
    pub fn Cronet_HttpHeader_name_set(self_: Cronet_HttpHeaderPtr, name: Cronet_String);
    pub fn Cronet_HttpHeader_value_set(self_: Cronet_HttpHeaderPtr, value: Cronet_String);
    /// Cronet_HttpHeader getters.
    pub fn Cronet_HttpHeader_name_get(self_: Cronet_HttpHeaderPtr) -> Cronet_String;
    pub fn Cronet_HttpHeader_value_get(self_: Cronet_HttpHeaderPtr) -> Cronet_String;
    /// Struct Cronet_UrlResponseInfo.
    pub fn Cronet_UrlResponseInfo_Create() -> Cronet_UrlResponseInfoPtr;
    pub fn Cronet_UrlResponseInfo_Destroy(self_: Cronet_UrlResponseInfoPtr);
    /// Cronet_UrlResponseInfo setters.
    pub fn Cronet_UrlResponseInfo_url_set(self_: Cronet_UrlResponseInfoPtr, url: Cronet_String);
    pub fn Cronet_UrlResponseInfo_url_chain_add(self_: Cronet_UrlResponseInfoPtr, element: Cronet_String);
    pub fn Cronet_UrlResponseInfo_http_status_code_set(self_: Cronet_UrlResponseInfoPtr, http_status_code: i32);
    pub fn Cronet_UrlResponseInfo_http_status_text_set(
        self_: Cronet_UrlResponseInfoPtr,
        http_status_text: Cronet_String,
    );
    pub fn Cronet_UrlResponseInfo_all_headers_list_add(self_: Cronet_UrlResponseInfoPtr, element: Cronet_HttpHeaderPtr);
    pub fn Cronet_UrlResponseInfo_was_cached_set(self_: Cronet_UrlResponseInfoPtr, was_cached: bool);
    pub fn Cronet_UrlResponseInfo_negotiated_protocol_set(
        self_: Cronet_UrlResponseInfoPtr,
        negotiated_protocol: Cronet_String,
    );
    pub fn Cronet_UrlResponseInfo_proxy_server_set(self_: Cronet_UrlResponseInfoPtr, proxy_server: Cronet_String);
    pub fn Cronet_UrlResponseInfo_received_byte_count_set(self_: Cronet_UrlResponseInfoPtr, received_byte_count: i64);
    /// Cronet_UrlResponseInfo getters.
    pub fn Cronet_UrlResponseInfo_url_get(self_: Cronet_UrlResponseInfoPtr) -> Cronet_String;
    pub fn Cronet_UrlResponseInfo_url_chain_size(self_: Cronet_UrlResponseInfoPtr) -> u32;
    pub fn Cronet_UrlResponseInfo_url_chain_at(self_: Cronet_UrlResponseInfoPtr, index: u32) -> Cronet_String;
    pub fn Cronet_UrlResponseInfo_url_chain_clear(self_: Cronet_UrlResponseInfoPtr);
    pub fn Cronet_UrlResponseInfo_http_status_code_get(self_: Cronet_UrlResponseInfoPtr) -> i32;
    pub fn Cronet_UrlResponseInfo_http_status_text_get(self_: Cronet_UrlResponseInfoPtr) -> Cronet_String;
    pub fn Cronet_UrlResponseInfo_all_headers_list_size(self_: Cronet_UrlResponseInfoPtr) -> u32;
    pub fn Cronet_UrlResponseInfo_all_headers_list_at(
        self_: Cronet_UrlResponseInfoPtr,
        index: u32,
    ) -> Cronet_HttpHeaderPtr;
    pub fn Cronet_UrlResponseInfo_all_headers_list_clear(self_: Cronet_UrlResponseInfoPtr);
    pub fn Cronet_UrlResponseInfo_was_cached_get(self_: Cronet_UrlResponseInfoPtr) -> bool;
    pub fn Cronet_UrlResponseInfo_negotiated_protocol_get(self_: Cronet_UrlResponseInfoPtr) -> Cronet_String;
    pub fn Cronet_UrlResponseInfo_proxy_server_get(self_: Cronet_UrlResponseInfoPtr) -> Cronet_String;
    pub fn Cronet_UrlResponseInfo_received_byte_count_get(self_: Cronet_UrlResponseInfoPtr) -> i64;
    /// Struct Cronet_UrlRequestParams.
    pub fn Cronet_UrlRequestParams_Create() -> Cronet_UrlRequestParamsPtr;
    pub fn Cronet_UrlRequestParams_Destroy(self_: Cronet_UrlRequestParamsPtr);
    /// Cronet_UrlRequestParams setters.
    pub fn Cronet_UrlRequestParams_http_method_set(self_: Cronet_UrlRequestParamsPtr, http_method: Cronet_String);
    pub fn Cronet_UrlRequestParams_request_headers_add(
        self_: Cronet_UrlRequestParamsPtr,
        element: Cronet_HttpHeaderPtr,
    );
    pub fn Cronet_UrlRequestParams_disable_cache_set(self_: Cronet_UrlRequestParamsPtr, disable_cache: bool);
    pub fn Cronet_UrlRequestParams_priority_set(
        self_: Cronet_UrlRequestParamsPtr,
        priority: Cronet_UrlRequestParams_REQUEST_PRIORITY,
    );
    pub fn Cronet_UrlRequestParams_upload_data_provider_set(
        self_: Cronet_UrlRequestParamsPtr,
        upload_data_provider: Cronet_UploadDataProviderPtr,
    );
    pub fn Cronet_UrlRequestParams_upload_data_provider_executor_set(
        self_: Cronet_UrlRequestParamsPtr,
        upload_data_provider_executor: Cronet_ExecutorPtr,
    );
    pub fn Cronet_UrlRequestParams_allow_direct_executor_set(
        self_: Cronet_UrlRequestParamsPtr,
        allow_direct_executor: bool,
    );
    pub fn Cronet_UrlRequestParams_annotations_add(self_: Cronet_UrlRequestParamsPtr, element: Cronet_RawDataPtr);
    pub fn Cronet_UrlRequestParams_request_finished_listener_set(
        self_: Cronet_UrlRequestParamsPtr,
        request_finished_listener: Cronet_RequestFinishedInfoListenerPtr,
    );
    pub fn Cronet_UrlRequestParams_request_finished_executor_set(
        self_: Cronet_UrlRequestParamsPtr,
        request_finished_executor: Cronet_ExecutorPtr,
    );
    pub fn Cronet_UrlRequestParams_idempotency_set(
        self_: Cronet_UrlRequestParamsPtr,
        idempotency: Cronet_UrlRequestParams_IDEMPOTENCY,
    );
    /// Cronet_UrlRequestParams getters.
    pub fn Cronet_UrlRequestParams_http_method_get(self_: Cronet_UrlRequestParamsPtr) -> Cronet_String;
    pub fn Cronet_UrlRequestParams_request_headers_size(self_: Cronet_UrlRequestParamsPtr) -> u32;
    pub fn Cronet_UrlRequestParams_request_headers_at(
        self_: Cronet_UrlRequestParamsPtr,
        index: u32,
    ) -> Cronet_HttpHeaderPtr;
    pub fn Cronet_UrlRequestParams_request_headers_clear(self_: Cronet_UrlRequestParamsPtr);
    pub fn Cronet_UrlRequestParams_disable_cache_get(self_: Cronet_UrlRequestParamsPtr) -> bool;
    pub fn Cronet_UrlRequestParams_priority_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_UrlRequestParams_REQUEST_PRIORITY;
    pub fn Cronet_UrlRequestParams_upload_data_provider_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_UploadDataProviderPtr;
    pub fn Cronet_UrlRequestParams_upload_data_provider_executor_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_ExecutorPtr;
    pub fn Cronet_UrlRequestParams_allow_direct_executor_get(self_: Cronet_UrlRequestParamsPtr) -> bool;
    pub fn Cronet_UrlRequestParams_annotations_size(self_: Cronet_UrlRequestParamsPtr) -> u32;
    pub fn Cronet_UrlRequestParams_annotations_at(self_: Cronet_UrlRequestParamsPtr, index: u32) -> Cronet_RawDataPtr;
    pub fn Cronet_UrlRequestParams_annotations_clear(self_: Cronet_UrlRequestParamsPtr);
    pub fn Cronet_UrlRequestParams_request_finished_listener_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_RequestFinishedInfoListenerPtr;
    pub fn Cronet_UrlRequestParams_request_finished_executor_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_ExecutorPtr;
    pub fn Cronet_UrlRequestParams_idempotency_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_UrlRequestParams_IDEMPOTENCY;
    /// Struct Cronet_DateTime.
    pub fn Cronet_DateTime_Create() -> Cronet_DateTimePtr;
    pub fn Cronet_DateTime_Destroy(self_: Cronet_DateTimePtr);
    /// Cronet_DateTime setters.
    pub fn Cronet_DateTime_value_set(self_: Cronet_DateTimePtr, value: i64);
    /// Cronet_DateTime getters.
    pub fn Cronet_DateTime_value_get(self_: Cronet_DateTimePtr) -> i64;
    /// Struct Cronet_Metrics.
    pub fn Cronet_Metrics_Create() -> Cronet_MetricsPtr;
    pub fn Cronet_Metrics_Destroy(self_: Cronet_MetricsPtr);
    /// Cronet_Metrics setters.
    pub fn Cronet_Metrics_request_start_set(self_: Cronet_MetricsPtr, request_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_dns_start_set(self_: Cronet_MetricsPtr, dns_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_dns_end_set(self_: Cronet_MetricsPtr, dns_end: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_connect_start_set(self_: Cronet_MetricsPtr, connect_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_connect_end_set(self_: Cronet_MetricsPtr, connect_end: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_ssl_start_set(self_: Cronet_MetricsPtr, ssl_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_ssl_end_set(self_: Cronet_MetricsPtr, ssl_end: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_sending_start_set(self_: Cronet_MetricsPtr, sending_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_sending_end_set(self_: Cronet_MetricsPtr, sending_end: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_push_start_set(self_: Cronet_MetricsPtr, push_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_push_end_set(self_: Cronet_MetricsPtr, push_end: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_response_start_set(self_: Cronet_MetricsPtr, response_start: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_request_end_set(self_: Cronet_MetricsPtr, request_end: Cronet_DateTimePtr);
    pub fn Cronet_Metrics_socket_reused_set(self_: Cronet_MetricsPtr, socket_reused: bool);
    pub fn Cronet_Metrics_sent_byte_count_set(self_: Cronet_MetricsPtr, sent_byte_count: i64);
    pub fn Cronet_Metrics_received_byte_count_set(self_: Cronet_MetricsPtr, received_byte_count: i64);
    /// Cronet_Metrics getters.
    pub fn Cronet_Metrics_request_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_dns_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_dns_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_connect_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_connect_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_ssl_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_ssl_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_sending_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_sending_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_push_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_push_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_response_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_request_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
    pub fn Cronet_Metrics_socket_reused_get(self_: Cronet_MetricsPtr) -> bool;
    pub fn Cronet_Metrics_sent_byte_count_get(self_: Cronet_MetricsPtr) -> i64;
    pub fn Cronet_Metrics_received_byte_count_get(self_: Cronet_MetricsPtr) -> i64;
    /// Struct Cronet_RequestFinishedInfo.
    pub fn Cronet_RequestFinishedInfo_Create() -> Cronet_RequestFinishedInfoPtr;
    pub fn Cronet_RequestFinishedInfo_Destroy(self_: Cronet_RequestFinishedInfoPtr);
    /// Cronet_RequestFinishedInfo setters.
    pub fn Cronet_RequestFinishedInfo_metrics_set(self_: Cronet_RequestFinishedInfoPtr, metrics: Cronet_MetricsPtr);
    pub fn Cronet_RequestFinishedInfo_annotations_add(self_: Cronet_RequestFinishedInfoPtr, element: Cronet_RawDataPtr);
    pub fn Cronet_RequestFinishedInfo_finished_reason_set(
        self_: Cronet_RequestFinishedInfoPtr,
        finished_reason: Cronet_RequestFinishedInfo_FINISHED_REASON,
    );
    /// Cronet_RequestFinishedInfo getters.
    pub fn Cronet_RequestFinishedInfo_metrics_get(self_: Cronet_RequestFinishedInfoPtr) -> Cronet_MetricsPtr;
    pub fn Cronet_RequestFinishedInfo_annotations_size(self_: Cronet_RequestFinishedInfoPtr) -> u32;
    pub fn Cronet_RequestFinishedInfo_annotations_at(
        self_: Cronet_RequestFinishedInfoPtr,
        index: u32,
    ) -> Cronet_RawDataPtr;
    pub fn Cronet_RequestFinishedInfo_annotations_clear(self_: Cronet_RequestFinishedInfoPtr);
    pub fn Cronet_RequestFinishedInfo_finished_reason_get(
        self_: Cronet_RequestFinishedInfoPtr,
    ) -> Cronet_RequestFinishedInfo_FINISHED_REASON;
    /// Sets net::CertVerifier* raw_mock_cert_verifier for testing of Cronet_Engine.
    /// Must be called before Cronet_Engine_InitWithParams().
    pub fn Cronet_Engine_SetMockCertVerifierForTesting(engine: Cronet_EnginePtr, raw_mock_cert_verifier: *mut c_void);
    /// Returns "stream_engine" interface for bidirectionsl stream support for GRPC.
    /// Returned stream engine is owned by Cronet Engine and is only valid until
    /// Cronet_Engine_Shutdown().
    pub fn Cronet_Engine_GetStreamEngine(engine: Cronet_EnginePtr) -> *mut stream_engine;
    /// Creates a CertVerifier that uses custom root certificates for validation.
    /// pem_root_certs: PEM-formatted root certificates (can contain multiple certs).
    /// Returns a pointer to the created net::CertVerifier.
    /// The caller is responsible for passing it to
    /// Cronet_Engine_SetMockCertVerifierForTesting() which takes ownership.
    /// Returns nullptr if the PEM data is invalid or no valid certificates found.
    pub fn Cronet_CreateCertVerifierWithRootCerts(pem_root_certs: *const c_char) -> *mut c_void;
    /// Sets a custom dialer for TCP connections.
    /// When set, the engine will use this callback to establish TCP connections
    /// instead of the default system socket API.
    /// Must be called before Cronet_Engine_StartWithParams().
    /// dialer: The callback function to use for TCP connections, or nullptr to
    /// disable custom dialing.
    /// context: User-provided context pointer that will be passed to the dialer.
    pub fn Cronet_Engine_SetDialer(engine: Cronet_EnginePtr, dialer: Cronet_DialerFunc, context: *mut c_void);
    /// Sets a custom dialer for UDP sockets.
    /// When set, the engine will use this callback to create UDP sockets
    /// instead of the default system socket API.
    /// Must be called before Cronet_Engine_StartWithParams().
    /// dialer: The callback function to use for UDP sockets, or nullptr to
    /// disable custom UDP dialing.
    /// context: User-provided context pointer that will be passed to the dialer.
    pub fn Cronet_Engine_SetUdpDialer(
        engine: Cronet_EnginePtr,
        dialer: Cronet_UdpDialerFunc,
        context: *mut c_void,
        on_close: Cronet_UdpSocketCloseFunc,
    );
    /// Closes all connections managed by the engine's network session.
    /// This includes socket pools, HTTP stream pool, SPDY session pool,
    /// and QUIC session pool. Useful for releasing connection-related memory
    /// or speeding up engine shutdown.
    /// Must be called after Cronet_Engine_StartWithParams().
    /// Calls from Cronet's network thread schedule the close asynchronously.
    pub fn Cronet_Engine_CloseAllConnections(engine: Cronet_EnginePtr);
    /// Creates a new stream object that uses |engine| and |callback|. All stream
    /// tasks are performed asynchronously on the |engine| network thread. |callback|
    /// methods are invoked synchronously on the |engine| network thread, but must
    /// not run tasks on the current thread to prevent blocking networking operations
    /// and causing exceptions during shutdown. The |annotation| is stored in
    /// bidirectional stream for arbitrary use by application.
    ///
    /// Returned |bidirectional_stream*| is owned by the caller, and must be
    /// destroyed using |bidirectional_stream_destroy|.
    ///
    /// Both |calback| and |engine| must remain valid until stream is destroyed.
    pub fn bidirectional_stream_create(
        engine: *mut stream_engine,
        annotation: *mut c_void,
        callback: *const bidirectional_stream_callback,
    ) -> *mut bidirectional_stream;
    /// Destroys stream object. Destroy could be called from any thread, including
    /// network thread, but is posted, so |stream| is valid until calling task is
    /// complete.
    pub fn bidirectional_stream_destroy(stream: *mut bidirectional_stream) -> c_int;
    /// Disables or enables auto flush. By default, data is flushed after
    /// every bidirectional_stream_write(). If the auto flush is disabled,
    /// the client should explicitly call bidirectional_stream_flush to flush
    /// the data.
    pub fn bidirectional_stream_disable_auto_flush(stream: *mut bidirectional_stream, disable_auto_flush: bool);
    /// Delays sending request headers until bidirectional_stream_flush()
    /// is called. This flag is currently only respected when QUIC is negotiated.
    /// When true, QUIC will send request header frame along with data frame(s)
    /// as a single packet when possible.
    pub fn bidirectional_stream_delay_request_headers_until_flush(
        stream: *mut bidirectional_stream,
        delay_headers_until_flush: bool,
    );
    /// Starts the stream by sending request to |url| using |method| and |headers|.
    /// If |end_of_stream| is true, then no data is expected to be written. The
    /// |method| is HTTP verb.
    pub fn bidirectional_stream_start(
        stream: *mut bidirectional_stream,
        url: *const c_char,
        priority: c_int,
        method: *const c_char,
        headers: *const bidirectional_stream_header_array,
        end_of_stream: bool,
    ) -> c_int;
    /// Reads response data into |buffer| of |capacity| length. Must only be called
    /// at most once in response to each invocation of the
    /// on_stream_ready()/on_response_headers_received() and on_read_completed()
    /// methods of the bidirectional_stream_callback.
    /// Each call will result in an invocation of the callback's
    /// on_read_completed() method if data is read, or its on_failed() method if
    /// there's an error. The callback's on_succeeded() method is also invoked if
    /// there is no more data to read and |end_of_stream| was previously sent.
    pub fn bidirectional_stream_read(stream: *mut bidirectional_stream, buffer: *mut c_char, capacity: c_int) -> c_int;
    /// Writes request data from |buffer| of |buffer_length| length. If auto flush is
    /// disabled, data will be sent only after bidirectional_stream_flush() is
    /// called.
    /// Each call will result in an invocation the callback's on_write_completed()
    /// method if data is sent, or its on_failed() method if there's an error.
    /// The callback's on_succeeded() method is also invoked if |end_of_stream| is
    /// set and all response data has been read.
    pub fn bidirectional_stream_write(
        stream: *mut bidirectional_stream,
        buffer: *const c_char,
        buffer_length: c_int,
        end_of_stream: bool,
    ) -> c_int;
    /// Flushes pending writes. This method should not be called before invocation of
    /// on_stream_ready() method of the bidirectional_stream_callback.
    /// For each previously called bidirectional_stream_write()
    /// a corresponding on_write_completed() callback will be invoked when the buffer
    /// is sent.
    pub fn bidirectional_stream_flush(stream: *mut bidirectional_stream);
    /// Cancels the stream. Can be called at any time after
    /// bidirectional_stream_start(). The on_canceled() method of
    /// bidirectional_stream_callback will be invoked when cancelation
    /// is complete and no further callback methods will be invoked. If the
    /// stream has completed or has not started, calling
    /// bidirectional_stream_cancel() has no effect and on_canceled() will not
    /// be invoked. At most one callback method may be invoked after
    /// bidirectional_stream_cancel() has completed.
    pub fn bidirectional_stream_cancel(stream: *mut bidirectional_stream);
}
