// @generated by `cargo xtask net-errors` from Chromium's `net/base/net_error_list.h`.
// Do not edit.

use super::{Entry, NetError};

impl NetError {
    /// An asynchronous IO operation is not yet complete.  This usually does not indicate a fatal error.  Typically this error will be generated as a notification to wait for some external notification that the IO operation finally completed.
    pub const IO_PENDING: Self = Self(-1);
    /// A generic failure occurred.
    pub const FAILED: Self = Self(-2);
    /// An operation was aborted (due to user action).
    pub const ABORTED: Self = Self(-3);
    /// An argument to the function is incorrect.
    pub const INVALID_ARGUMENT: Self = Self(-4);
    /// The handle or file descriptor is invalid.
    pub const INVALID_HANDLE: Self = Self(-5);
    /// The file or directory cannot be found.
    pub const FILE_NOT_FOUND: Self = Self(-6);
    /// An operation timed out.
    pub const TIMED_OUT: Self = Self(-7);
    /// The file is too large.
    pub const FILE_TOO_BIG: Self = Self(-8);
    /// An unexpected error.  This may be caused by a programming mistake or an invalid assumption.
    pub const UNEXPECTED: Self = Self(-9);
    /// Permission to access a resource, other than the network, was denied.
    pub const ACCESS_DENIED: Self = Self(-10);
    /// The operation failed because of unimplemented functionality.
    pub const NOT_IMPLEMENTED: Self = Self(-11);
    /// There were not enough resources to complete the operation.
    pub const INSUFFICIENT_RESOURCES: Self = Self(-12);
    /// Memory allocation failed.
    pub const OUT_OF_MEMORY: Self = Self(-13);
    /// The file upload failed because the file's modification time was different from the expectation.
    pub const UPLOAD_FILE_CHANGED: Self = Self(-14);
    /// The socket is not connected.
    pub const SOCKET_NOT_CONNECTED: Self = Self(-15);
    /// The file already exists.
    pub const FILE_EXISTS: Self = Self(-16);
    /// The path or file name is too long.
    pub const FILE_PATH_TOO_LONG: Self = Self(-17);
    /// Not enough room left on the disk.
    pub const FILE_NO_SPACE: Self = Self(-18);
    /// The file has a virus.
    pub const FILE_VIRUS_INFECTED: Self = Self(-19);
    /// The client chose to block the request.
    pub const BLOCKED_BY_CLIENT: Self = Self(-20);
    /// The network changed.
    pub const NETWORK_CHANGED: Self = Self(-21);
    /// The request was blocked by the URL block list configured by the domain administrator.
    pub const BLOCKED_BY_ADMINISTRATOR: Self = Self(-22);
    /// The socket is already connected.
    pub const SOCKET_IS_CONNECTED: Self = Self(-23);
    /// The upload failed because the upload stream needed to be re-read, due to a retry or a redirect, but the upload stream doesn't support that operation.
    pub const UPLOAD_STREAM_REWIND_NOT_SUPPORTED: Self = Self(-25);
    /// The request failed because the URLRequestContext is shutting down, or has been shut down.
    pub const CONTEXT_SHUT_DOWN: Self = Self(-26);
    /// The request failed because the response was delivered along with requirements which are not met ('X-Frame-Options' and 'Content-Security-Policy' ancestor checks and 'Cross-Origin-Resource-Policy' for instance).
    pub const BLOCKED_BY_RESPONSE: Self = Self(-27);
    /// The request was blocked by system policy disallowing some or all cleartext requests. Used for NetworkSecurityPolicy on Android.
    pub const CLEARTEXT_NOT_PERMITTED: Self = Self(-29);
    /// The request was blocked by a Content Security Policy
    pub const BLOCKED_BY_CSP: Self = Self(-30);
    /// The request was blocked by CORB or ORB.
    pub const BLOCKED_BY_ORB: Self = Self(-32);
    /// The request was blocked because it originated from a frame that has disabled network access.
    pub const NETWORK_ACCESS_REVOKED: Self = Self(-33);
    /// The request was blocked by fingerprinting protections.
    pub const BLOCKED_BY_FINGERPRINTING_PROTECTION: Self = Self(-34);
    /// The request was blocked by the Incognito Mode URL block list configured by the domain administrator.
    pub const BLOCKED_IN_INCOGNITO_BY_ADMINISTRATOR: Self = Self(-35);
    /// The request was blocked because the local network permission is missing. Note that this is different from BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS which is specifically for a CORS error code.
    pub const LOCAL_NETWORK_PERMISSION_MISSING: Self = Self(-36);
    /// The request was blocked because ECH is strictly required, but: - The client could not obtain a valid ECH configuration. - The server rejected the ECH, and the client failed to establish a new ECH connection after retrying with retry_configs.
    pub const STRICT_ECH_REQUIRED: Self = Self(-37);
    /// A connection was closed (corresponding to a TCP FIN).
    pub const CONNECTION_CLOSED: Self = Self(-100);
    /// A connection was reset (corresponding to a TCP RST).
    pub const CONNECTION_RESET: Self = Self(-101);
    /// A connection attempt was refused.
    pub const CONNECTION_REFUSED: Self = Self(-102);
    /// A connection timed out as a result of not receiving an ACK for data sent. This can include a FIN packet that did not get ACK'd.
    pub const CONNECTION_ABORTED: Self = Self(-103);
    /// A connection attempt failed.
    pub const CONNECTION_FAILED: Self = Self(-104);
    /// The host name could not be resolved.
    pub const NAME_NOT_RESOLVED: Self = Self(-105);
    /// The Internet connection has been lost.
    pub const INTERNET_DISCONNECTED: Self = Self(-106);
    /// An SSL protocol error occurred.
    pub const SSL_PROTOCOL_ERROR: Self = Self(-107);
    /// The IP address or port number is invalid (e.g., cannot connect to the IP address 0 or the port 0).
    pub const ADDRESS_INVALID: Self = Self(-108);
    /// The IP address is unreachable.  This usually means that there is no route to the specified host or network.
    pub const ADDRESS_UNREACHABLE: Self = Self(-109);
    /// The server requested a client certificate for SSL client authentication.
    pub const SSL_CLIENT_AUTH_CERT_NEEDED: Self = Self(-110);
    /// A tunnel connection through the proxy could not be established. For more info see the comment on PROXY_UNABLE_TO_CONNECT_TO_DESTINATION.
    pub const TUNNEL_CONNECTION_FAILED: Self = Self(-111);
    /// The client and server don't support a common SSL protocol version or cipher suite.
    pub const SSL_VERSION_OR_CIPHER_MISMATCH: Self = Self(-113);
    /// The server requested a renegotiation (rehandshake).
    pub const SSL_RENEGOTIATION_REQUESTED: Self = Self(-114);
    /// The proxy requested authentication (for tunnel establishment) with an unsupported method.
    pub const PROXY_AUTH_UNSUPPORTED: Self = Self(-115);
    /// The SSL handshake failed because of a bad or missing client certificate.
    pub const BAD_SSL_CLIENT_AUTH_CERT: Self = Self(-117);
    /// A connection attempt timed out.
    pub const CONNECTION_TIMED_OUT: Self = Self(-118);
    /// There are too many pending DNS resolves, so a request in the queue was aborted.
    pub const HOST_RESOLVER_QUEUE_TOO_LARGE: Self = Self(-119);
    /// Failed establishing a connection to the SOCKS proxy server for a target host.
    pub const SOCKS_CONNECTION_FAILED: Self = Self(-120);
    /// The SOCKS proxy server failed establishing connection to the target host because that host is unreachable.
    pub const SOCKS_CONNECTION_HOST_UNREACHABLE: Self = Self(-121);
    /// The request to negotiate an alternate protocol failed.
    pub const ALPN_NEGOTIATION_FAILED: Self = Self(-122);
    /// The peer sent an SSL no_renegotiation alert message.
    pub const SSL_NO_RENEGOTIATION: Self = Self(-123);
    /// Winsock sometimes reports more data written than passed.  This is probably due to a broken LSP.
    pub const WINSOCK_UNEXPECTED_WRITTEN_BYTES: Self = Self(-124);
    /// An SSL peer sent us a fatal decompression_failure alert. This typically occurs when a peer selects DEFLATE compression in the mistaken belief that it supports it.
    pub const SSL_DECOMPRESSION_FAILURE_ALERT: Self = Self(-125);
    /// An SSL peer sent us a fatal bad_record_mac alert. This has been observed from servers with buggy DEFLATE support.
    pub const SSL_BAD_RECORD_MAC_ALERT: Self = Self(-126);
    /// The proxy requested authentication (for tunnel establishment).
    pub const PROXY_AUTH_REQUESTED: Self = Self(-127);
    /// Could not create a connection to the proxy server. An error occurred either in resolving its name, or in connecting a socket to it. Note that this does NOT include failures during the actual "CONNECT" method of an HTTP proxy.
    pub const PROXY_CONNECTION_FAILED: Self = Self(-130);
    /// A mandatory proxy configuration could not be used. Currently this means that a mandatory PAC script could not be fetched, parsed or executed.
    pub const MANDATORY_PROXY_CONFIGURATION_FAILED: Self = Self(-131);
    /// We've hit the max socket limit for the socket pool while preconnecting.  We don't bother trying to preconnect more sockets.
    pub const PRECONNECT_MAX_SOCKET_LIMIT: Self = Self(-133);
    /// The permission to use the SSL client certificate's private key was denied.
    pub const SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED: Self = Self(-134);
    /// The SSL client certificate has no private key.
    pub const SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY: Self = Self(-135);
    /// The certificate presented by the HTTPS Proxy was invalid.
    pub const PROXY_CERTIFICATE_INVALID: Self = Self(-136);
    /// An error occurred when trying to do a name resolution (DNS).
    pub const NAME_RESOLUTION_FAILED: Self = Self(-137);
    /// Permission to access the network was denied. This is used to distinguish errors that were most likely caused by a firewall from other access denied errors. See also ERR_ACCESS_DENIED.
    pub const NETWORK_ACCESS_DENIED: Self = Self(-138);
    /// The request throttler module cancelled this request to avoid DDOS.
    pub const TEMPORARILY_THROTTLED: Self = Self(-139);
    /// We were unable to sign the CertificateVerify data of an SSL client auth handshake with the client certificate's private key. Possible causes for this include the user implicitly or explicitly denying access to the private key, the private key may not be valid for signing, the key may be relying on a cached handle which is no longer valid, or the CSP won't allow arbitrary data to be signed.
    pub const SSL_CLIENT_AUTH_SIGNATURE_FAILED: Self = Self(-141);
    /// The message was too large for the transport.  (for example a UDP message which exceeds size threshold).
    pub const MSG_TOO_BIG: Self = Self(-142);
    /// Websocket protocol error. Indicates that we are terminating the connection due to a malformed frame or other protocol violation.
    pub const WS_PROTOCOL_ERROR: Self = Self(-145);
    /// Returned when attempting to bind an address that is already in use.
    pub const ADDRESS_IN_USE: Self = Self(-147);
    /// The certificate didn't match the built-in public key pins for the host name. The pins are set in net/http/transport_security_state.cc and require that one of a set of public keys exist on the path from the leaf to the root.
    pub const SSL_PINNED_KEY_NOT_IN_CERT_CHAIN: Self = Self(-150);
    /// Server request for client certificate did not contain any types we support.
    pub const CLIENT_AUTH_CERT_TYPE_UNSUPPORTED: Self = Self(-151);
    /// An SSL peer sent us a fatal decrypt_error alert. This typically occurs when a peer could not correctly verify a signature (in CertificateVerify or ServerKeyExchange) or validate a Finished message.
    pub const SSL_DECRYPT_ERROR_ALERT: Self = Self(-153);
    /// There are too many pending WebSocketJob instances, so the new job was not pushed to the queue.
    pub const WS_THROTTLE_QUEUE_TOO_LARGE: Self = Self(-154);
    /// The SSL server certificate changed in a renegotiation.
    pub const SSL_SERVER_CERT_CHANGED: Self = Self(-156);
    /// The SSL server sent us a fatal unrecognized_name alert.
    pub const SSL_UNRECOGNIZED_NAME_ALERT: Self = Self(-159);
    /// Failed to set the socket's receive buffer size as requested.
    pub const SOCKET_SET_RECEIVE_BUFFER_SIZE_ERROR: Self = Self(-160);
    /// Failed to set the socket's send buffer size as requested.
    pub const SOCKET_SET_SEND_BUFFER_SIZE_ERROR: Self = Self(-161);
    /// Failed to set the socket's receive buffer size as requested, despite success return code from setsockopt.
    pub const SOCKET_RECEIVE_BUFFER_SIZE_UNCHANGEABLE: Self = Self(-162);
    /// Failed to set the socket's send buffer size as requested, despite success return code from setsockopt.
    pub const SOCKET_SEND_BUFFER_SIZE_UNCHANGEABLE: Self = Self(-163);
    /// Failed to import a client certificate from the platform store into the SSL library.
    pub const SSL_CLIENT_AUTH_CERT_BAD_FORMAT: Self = Self(-164);
    /// Resolving a hostname to an IP address list included the IPv4 address "127.0.53.53". This is a special IP address which ICANN has recommended to indicate there was a name collision, and alert admins to a potential problem.
    pub const ICANN_NAME_COLLISION: Self = Self(-166);
    /// The SSL server presented a certificate which could not be decoded. This is not a certificate error code as no X509Certificate object is available. This error is fatal.
    pub const SSL_SERVER_CERT_BAD_FORMAT: Self = Self(-167);
    /// Certificate Transparency: Received a signed tree head that failed to parse.
    pub const CT_STH_PARSING_FAILED: Self = Self(-168);
    /// Certificate Transparency: Received a signed tree head whose JSON parsing was OK but was missing some of the fields.
    pub const CT_STH_INCOMPLETE: Self = Self(-169);
    /// The attempt to reuse a connection to send proxy auth credentials failed before the AuthController was used to generate credentials. The caller should reuse the controller with a new connection. This error is only used internally by the network stack.
    pub const UNABLE_TO_REUSE_CONNECTION_FOR_PROXY_AUTH: Self = Self(-170);
    /// Certificate Transparency: Failed to parse the received consistency proof.
    pub const CT_CONSISTENCY_PROOF_PARSING_FAILED: Self = Self(-171);
    /// The SSL server required an unsupported cipher suite that has since been removed. This error will temporarily be signaled on a fallback for one or two releases immediately following a cipher suite's removal, after which the fallback will be removed.
    pub const SSL_OBSOLETE_CIPHER: Self = Self(-172);
    /// When a WebSocket handshake is done successfully and the connection has been upgraded, the URLRequest is cancelled with this error code.
    pub const WS_UPGRADE: Self = Self(-173);
    /// Socket ReadIfReady support is not implemented. This error should not be user visible, because the normal Read() method is used as a fallback.
    pub const READ_IF_READY_NOT_IMPLEMENTED: Self = Self(-174);
    /// No socket buffer space is available.
    pub const NO_BUFFER_SPACE: Self = Self(-176);
    /// There were no common signature algorithms between our client certificate private key and the server's preferences.
    pub const SSL_CLIENT_AUTH_NO_COMMON_ALGORITHMS: Self = Self(-177);
    /// TLS 1.3 early data was rejected by the server. This will be received before any data is returned from the socket. The request should be retried with early data disabled.
    pub const EARLY_DATA_REJECTED: Self = Self(-178);
    /// TLS 1.3 early data was offered, but the server responded with TLS 1.2 or earlier. This is an internal error code to account for a backwards-compatibility issue with early data and TLS 1.2. It will be received before any data is returned from the socket. The request should be retried with early data disabled. See <https://tools.ietf.org/html/rfc8446#appendix-D.3> for details.
    pub const WRONG_VERSION_ON_EARLY_DATA: Self = Self(-179);
    /// TLS 1.3 was enabled, but a lower version was negotiated and the server returned a value indicating it supported TLS 1.3. This is part of a security check in TLS 1.3, but it may also indicate the user is behind a buggy TLS-terminating proxy which implemented TLS 1.2 incorrectly. (See <https://crbug.com/boringssl/226>.)
    pub const TLS13_DOWNGRADE_DETECTED: Self = Self(-180);
    /// The server's certificate has a keyUsage extension incompatible with the negotiated TLS key exchange method.
    pub const SSL_KEY_USAGE_INCOMPATIBLE: Self = Self(-181);
    /// The ECHConfigList fetched over DNS cannot be parsed.
    pub const INVALID_ECH_CONFIG_LIST: Self = Self(-182);
    /// ECH was enabled, but the server was unable to decrypt the encrypted ClientHello.
    pub const ECH_NOT_NEGOTIATED: Self = Self(-183);
    /// ECH was enabled, the server was unable to decrypt the encrypted ClientHello, and additionally did not present a certificate valid for the public name.
    pub const ECH_FALLBACK_CERTIFICATE_INVALID: Self = Self(-184);
    /// An attempt to proxy a request failed because the proxy wasn't able to successfully connect to the destination. This likely indicates an issue with the request itself (for instance, the hostname failed to resolve to an IP address or the destination server refused the connection). This error code is used to indicate that the error is outside the control of the proxy server and thus the proxy chain should not be marked as bad. This is in contrast to ERR_TUNNEL_CONNECTION_FAILED which is used for general purpose errors connecting to the proxy and by the proxy request response handling when a proxy delegate doesn't indicate via a different error code whether proxy fallback should occur. Note that for IP Protection proxies this error code causes the proxy to be marked as bad since the preference is to fail open for general purpose errors, but for other proxies this error does not cause the proxy to be marked as bad.
    pub const PROXY_UNABLE_TO_CONNECT_TO_DESTINATION: Self = Self(-186);
    /// Some implementations of ProxyDelegate query a separate entity to know whether it should cancel tunnel prior to: - The HTTP CONNECT requests being sent out - The HTTP CONNECT response being parsed by //net An example is CronetProxyDelegate: Cronet allows developers to decide whether the tunnel being established should be canceled.
    pub const PROXY_DELEGATE_CANCELED_CONNECT_REQUEST: Self = Self(-187);
    pub const PROXY_DELEGATE_CANCELED_CONNECT_RESPONSE: Self = Self(-188);
    /// The control message was too large for the transport. (for example a UDP message control data exceeds size threshold).
    pub const CONTROL_MSG_TOO_BIG: Self = Self(-189);
    /// Direct Sockets attempted to connect to or send a packet to a multicast address without 'direct-sockets-multicast' permissions policy.
    pub const MULTICAST_NOT_ALLOWED: Self = Self(-190);
    /// The server responded with a certificate whose common name did not match the host name.  This could mean: 1. An attacker has redirected our traffic to their server and is presenting a certificate for which they know the private key. 2. The server is misconfigured and responding with the wrong cert. 3. The user is on a wireless network and is being redirected to the network's login page. 4. The OS has used a DNS search suffix and the server doesn't have a certificate for the abbreviated name in the address bar.
    pub const CERT_COMMON_NAME_INVALID: Self = Self(-200);
    /// The server responded with a certificate that, by our clock, appears to either not yet be valid or to have expired.  This could mean: 1. An attacker is presenting an old certificate for which they have managed to obtain the private key. 2. The server is misconfigured and is not presenting a valid cert. 3. Our clock is wrong.
    pub const CERT_DATE_INVALID: Self = Self(-201);
    /// The server responded with a certificate that is signed by an authority we don't trust.  The could mean: 1. An attacker has substituted the real certificate for a cert that contains their public key and is signed by their cousin. 2. The server operator has a legitimate certificate from a CA we don't know about, but should trust. 3. The server is presenting a self-signed certificate, providing no defense against active attackers (but foiling passive attackers).
    pub const CERT_AUTHORITY_INVALID: Self = Self(-202);
    /// The server responded with a certificate that contains errors. This error is not recoverable. MSDN describes this error as follows: "The SSL certificate contains errors." NOTE: It's unclear how this differs from ERR_CERT_INVALID. For consistency, use that code instead of this one from now on.
    pub const CERT_CONTAINS_ERRORS: Self = Self(-203);
    /// The certificate has no mechanism for determining if it is revoked.  In effect, this certificate cannot be revoked.
    pub const CERT_NO_REVOCATION_MECHANISM: Self = Self(-204);
    /// Revocation information for the security certificate for this site is not available.  This could mean: 1. An attacker has compromised the private key in the certificate and is blocking our attempt to find out that the cert was revoked. 2. The certificate is unrevoked, but the revocation server is busy or unavailable.
    pub const CERT_UNABLE_TO_CHECK_REVOCATION: Self = Self(-205);
    /// The server responded with a certificate has been revoked. We have the capability to ignore this error, but it is probably not the thing to do.
    pub const CERT_REVOKED: Self = Self(-206);
    /// The server responded with a certificate that is invalid. This error is not recoverable. MSDN describes this error as follows: "The SSL certificate is invalid."
    pub const CERT_INVALID: Self = Self(-207);
    /// The server responded with a certificate that is signed using a weak signature algorithm.
    pub const CERT_WEAK_SIGNATURE_ALGORITHM: Self = Self(-208);
    /// The host name specified in the certificate is not unique.
    pub const CERT_NON_UNIQUE_NAME: Self = Self(-210);
    /// The server responded with a certificate that contains a weak key (e.g. a too-small RSA key).
    pub const CERT_WEAK_KEY: Self = Self(-211);
    /// The certificate claimed DNS names that are in violation of name constraints.
    pub const CERT_NAME_CONSTRAINT_VIOLATION: Self = Self(-212);
    /// The certificate's validity period is too long.
    pub const CERT_VALIDITY_TOO_LONG: Self = Self(-213);
    /// Certificate Transparency was required for this connection, but the server did not provide CT information that complied with the policy.
    pub const CERTIFICATE_TRANSPARENCY_REQUIRED: Self = Self(-214);
    /// The certificate is known to be used for interception by an entity other the device owner.
    pub const CERT_KNOWN_INTERCEPTION_BLOCKED: Self = Self(-217);
    /// The certificate is self signed and it's being used for either an RFC1918 IP literal URL, or a url ending in .local.
    pub const CERT_SELF_SIGNED_LOCAL_NETWORK: Self = Self(-219);
    /// The URL is invalid.
    pub const INVALID_URL: Self = Self(-300);
    /// The scheme of the URL is disallowed.
    pub const DISALLOWED_URL_SCHEME: Self = Self(-301);
    /// The scheme of the URL is unknown.
    pub const UNKNOWN_URL_SCHEME: Self = Self(-302);
    /// Attempting to load an URL resulted in a redirect to an invalid URL.
    pub const INVALID_REDIRECT: Self = Self(-303);
    /// Attempting to load an URL resulted in too many redirects.
    pub const TOO_MANY_REDIRECTS: Self = Self(-310);
    /// Attempting to load an URL resulted in an unsafe redirect (e.g., a redirect to file:// is considered unsafe).
    pub const UNSAFE_REDIRECT: Self = Self(-311);
    /// Attempting to load an URL with an unsafe port number.  These are port numbers that correspond to services, which are not robust to spurious input that may be constructed as a result of an allowed web construct (e.g., HTTP looks a lot like SMTP, so form submission to port 25 is denied).
    pub const UNSAFE_PORT: Self = Self(-312);
    /// The server's response was invalid.
    pub const INVALID_RESPONSE: Self = Self(-320);
    /// Error in chunked transfer encoding.
    pub const INVALID_CHUNKED_ENCODING: Self = Self(-321);
    /// The server did not support the request method.
    pub const METHOD_NOT_SUPPORTED: Self = Self(-322);
    /// The response was 407 (Proxy Authentication Required), yet we did not send the request to a proxy.
    pub const UNEXPECTED_PROXY_AUTH: Self = Self(-323);
    /// The server closed the connection without sending any data.
    pub const EMPTY_RESPONSE: Self = Self(-324);
    /// The headers section of the response is too large.
    pub const RESPONSE_HEADERS_TOO_BIG: Self = Self(-325);
    /// The evaluation of the PAC script failed.
    pub const PAC_SCRIPT_FAILED: Self = Self(-327);
    /// The response was 416 (Requested range not satisfiable) and the server cannot satisfy the range requested.
    pub const REQUEST_RANGE_NOT_SATISFIABLE: Self = Self(-328);
    /// The identity used for authentication is invalid.
    pub const MALFORMED_IDENTITY: Self = Self(-329);
    /// Content decoding of the response body failed.
    pub const CONTENT_DECODING_FAILED: Self = Self(-330);
    /// An operation could not be completed because all network IO is suspended.
    pub const NETWORK_IO_SUSPENDED: Self = Self(-331);
    /// There are no supported proxies in the provided list.
    pub const NO_SUPPORTED_PROXIES: Self = Self(-336);
    /// There is an HTTP/2 protocol error.
    pub const HTTP2_PROTOCOL_ERROR: Self = Self(-337);
    /// Credentials could not be established during HTTP Authentication.
    pub const INVALID_AUTH_CREDENTIALS: Self = Self(-338);
    /// An HTTP Authentication scheme was tried which is not supported on this machine.
    pub const UNSUPPORTED_AUTH_SCHEME: Self = Self(-339);
    /// Detecting the encoding of the response failed.
    pub const ENCODING_DETECTION_FAILED: Self = Self(-340);
    /// (GSSAPI) No Kerberos credentials were available during HTTP Authentication.
    pub const MISSING_AUTH_CREDENTIALS: Self = Self(-341);
    /// An unexpected, but documented, SSPI or GSSAPI status code was returned.
    pub const UNEXPECTED_SECURITY_LIBRARY_STATUS: Self = Self(-342);
    /// The environment was not set up correctly for authentication (for example, no KDC could be found or the principal is unknown.
    pub const MISCONFIGURED_AUTH_ENVIRONMENT: Self = Self(-343);
    /// An undocumented SSPI or GSSAPI status code was returned.
    pub const UNDOCUMENTED_SECURITY_LIBRARY_STATUS: Self = Self(-344);
    /// The HTTP response was too big to drain.
    pub const RESPONSE_BODY_TOO_BIG_TO_DRAIN: Self = Self(-345);
    /// The HTTP response contained multiple distinct Content-Length headers.
    pub const RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH: Self = Self(-346);
    /// HTTP/2 headers have been received, but not all of them - status or version headers are missing, so we're expecting additional frames to complete them.
    pub const INCOMPLETE_HTTP2_HEADERS: Self = Self(-347);
    /// No PAC URL configuration could be retrieved from DHCP. This can indicate either a failure to retrieve the DHCP configuration, or that there was no PAC URL configured in DHCP.
    pub const PAC_NOT_IN_DHCP: Self = Self(-348);
    /// The HTTP response contained multiple Content-Disposition headers.
    pub const RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION: Self = Self(-349);
    /// The HTTP response contained multiple Location headers.
    pub const RESPONSE_HEADERS_MULTIPLE_LOCATION: Self = Self(-350);
    /// HTTP/2 server refused the request without processing, and sent either a GOAWAY frame with error code NO_ERROR and Last-Stream-ID lower than the stream id corresponding to the request indicating that this request has not been processed yet, or a RST_STREAM frame with error code REFUSED_STREAM. Client MAY retry (on a different connection).  See RFC7540 Section 8.1.4.
    pub const HTTP2_SERVER_REFUSED_STREAM: Self = Self(-351);
    /// HTTP/2 server didn't respond to the PING message.
    pub const HTTP2_PING_FAILED: Self = Self(-352);
    /// The HTTP response body transferred fewer bytes than were advertised by the Content-Length header when the connection is closed.
    pub const CONTENT_LENGTH_MISMATCH: Self = Self(-354);
    /// The HTTP response body is transferred with Chunked-Encoding, but the terminating zero-length chunk was never sent when the connection is closed.
    pub const INCOMPLETE_CHUNKED_ENCODING: Self = Self(-355);
    /// There is a QUIC protocol error.
    pub const QUIC_PROTOCOL_ERROR: Self = Self(-356);
    /// The HTTP headers were truncated by an EOF.
    pub const RESPONSE_HEADERS_TRUNCATED: Self = Self(-357);
    /// The QUIC crypto handshake failed.  This means that the server was unable to read any requests sent, so they may be resent.
    pub const QUIC_HANDSHAKE_FAILED: Self = Self(-358);
    /// Transport security is inadequate for the HTTP/2 version.
    pub const HTTP2_INADEQUATE_TRANSPORT_SECURITY: Self = Self(-360);
    /// The peer violated HTTP/2 flow control.
    pub const HTTP2_FLOW_CONTROL_ERROR: Self = Self(-361);
    /// The peer sent an improperly sized HTTP/2 frame.
    pub const HTTP2_FRAME_SIZE_ERROR: Self = Self(-362);
    /// Decoding or encoding of compressed HTTP/2 headers failed.
    pub const HTTP2_COMPRESSION_ERROR: Self = Self(-363);
    /// Proxy Auth Requested without a valid Client Socket Handle.
    pub const PROXY_AUTH_REQUESTED_WITH_NO_CONNECTION: Self = Self(-364);
    /// HTTP_1_1_REQUIRED error code received on HTTP/2 session.
    pub const HTTP_1_1_REQUIRED: Self = Self(-365);
    /// HTTP_1_1_REQUIRED error code received on HTTP/2 session to proxy.
    pub const PROXY_HTTP_1_1_REQUIRED: Self = Self(-366);
    /// The PAC script terminated fatally and must be reloaded.
    pub const PAC_SCRIPT_TERMINATED: Self = Self(-367);
    /// The server was expected to return an HTTP/1.x response, but did not. Rather than treat it as HTTP/0.9, this error is returned.
    pub const INVALID_HTTP_RESPONSE: Self = Self(-370);
    /// Initializing content decoding failed.
    pub const CONTENT_DECODING_INIT_FAILED: Self = Self(-371);
    /// Received HTTP/2 RST_STREAM frame with NO_ERROR error code.  This error should be handled internally by HTTP/2 code, and should not make it above the SpdyStream layer.
    pub const HTTP2_RST_STREAM_NO_ERROR_RECEIVED: Self = Self(-372);
    /// An HTTP transaction was retried too many times due for authentication or invalid certificates. This may be due to a bug in the net stack that would otherwise infinite loop, or if the server or proxy continually requests fresh credentials or presents a fresh invalid certificate.
    pub const TOO_MANY_RETRIES: Self = Self(-375);
    /// Received an HTTP/2 frame on a closed stream.
    pub const HTTP2_STREAM_CLOSED: Self = Self(-376);
    /// The server returned a non-2xx HTTP response code. Note that this error is only used by certain APIs that interpret the HTTP response itself. URLRequest for instance just passes most non-2xx response back as success.
    pub const HTTP_RESPONSE_CODE_FAILURE: Self = Self(-379);
    /// The certificate presented on a QUIC connection does not chain to a known root and the origin connected to is not on a list of domains where unknown roots are allowed.
    pub const QUIC_CERT_ROOT_NOT_KNOWN: Self = Self(-380);
    /// A GOAWAY frame has been received indicating that the request has not been processed and is therefore safe to retry on a different connection.
    pub const QUIC_GOAWAY_REQUEST_CAN_BE_RETRIED: Self = Self(-381);
    /// The ACCEPT_CH restart has been triggered too many times
    pub const TOO_MANY_ACCEPT_CH_RESTARTS: Self = Self(-382);
    /// The IP address space of the remote endpoint differed from the previous observed value during the same request. Any cache entry for the affected request should be invalidated.
    pub const INCONSISTENT_IP_ADDRESS_SPACE: Self = Self(-383);
    /// The IP address space of the cached remote endpoint is blocked by private network access check.
    pub const CACHED_IP_ADDRESS_SPACE_BLOCKED_BY_LOCAL_NETWORK_ACCESS_POLICY: Self = Self(-384);
    /// The connection is blocked by private network access checks.
    pub const BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS: Self = Self(-385);
    /// Content decoding failed due to the zstd window size being too big (over 8MB).
    pub const ZSTD_WINDOW_SIZE_TOO_BIG: Self = Self(-386);
    /// The compression dictionary cannot be loaded.
    pub const DICTIONARY_LOAD_FAILED: Self = Self(-387);
    /// The header of dictionary compressed stream does not match the expected value.
    pub const UNEXPECTED_CONTENT_DICTIONARY_HEADER: Self = Self(-388);
    /// The cache does not have the requested entry.
    pub const CACHE_MISS: Self = Self(-400);
    /// Unable to read from the disk cache.
    pub const CACHE_READ_FAILURE: Self = Self(-401);
    /// Unable to write to the disk cache.
    pub const CACHE_WRITE_FAILURE: Self = Self(-402);
    /// The operation is not supported for this entry.
    pub const CACHE_OPERATION_NOT_SUPPORTED: Self = Self(-403);
    /// The disk cache is unable to open this entry.
    pub const CACHE_OPEN_FAILURE: Self = Self(-404);
    /// The disk cache is unable to create this entry.
    pub const CACHE_CREATE_FAILURE: Self = Self(-405);
    /// Multiple transactions are racing to create disk cache entries. This is an internal error returned from the HttpCache to the HttpCacheTransaction that tells the transaction to restart the entry-creation logic because the state of the cache has changed.
    pub const CACHE_RACE: Self = Self(-406);
    /// The cache was unable to read a checksum record on an entry. This can be returned from attempts to read from the cache. It is an internal error, returned by the SimpleCache backend, but not by any URLRequest methods or members.
    pub const CACHE_CHECKSUM_READ_FAILURE: Self = Self(-407);
    /// The cache found an entry with an invalid checksum. This can be returned from attempts to read from the cache. It is an internal error, returned by the SimpleCache backend, but not by any URLRequest methods or members.
    pub const CACHE_CHECKSUM_MISMATCH: Self = Self(-408);
    /// Internal error code for the HTTP cache. The cache lock timeout has fired.
    pub const CACHE_LOCK_TIMEOUT: Self = Self(-409);
    /// Received a challenge after the transaction has read some data, and the credentials aren't available.  There isn't a way to get them at that point.
    pub const CACHE_AUTH_FAILURE_AFTER_READ: Self = Self(-410);
    /// Internal not-quite error code for the HTTP cache. In-memory hints suggest that the cache entry would not have been usable with the transaction's current configuration (e.g. load flags, mode, etc.)
    pub const CACHE_ENTRY_NOT_SUITABLE: Self = Self(-411);
    /// The disk cache is unable to doom this entry.
    pub const CACHE_DOOM_FAILURE: Self = Self(-412);
    /// The disk cache is unable to open or create this entry.
    pub const CACHE_OPEN_OR_CREATE_FAILURE: Self = Self(-413);
    /// Zstd compression of a cache entry body failed.
    pub const CACHE_COMPRESSION_FAILURE: Self = Self(-414);
    /// The server's response was insecure (e.g. there was a cert error).
    pub const INSECURE_RESPONSE: Self = Self(-501);
    /// An attempt to import a client certificate failed, as the user's key database lacked a corresponding private key.
    pub const NO_PRIVATE_KEY_FOR_CERT: Self = Self(-502);
    /// An error adding a certificate to the OS certificate database.
    pub const ADD_USER_CERT_FAILED: Self = Self(-503);
    /// An error occurred while handling a signed exchange.
    pub const INVALID_SIGNED_EXCHANGE: Self = Self(-504);
    /// An error occurred while handling a Web Bundle source.
    pub const INVALID_WEB_BUNDLE: Self = Self(-505);
    /// A Trust Tokens protocol operation-executing request failed for one of a number of reasons (precondition failure, internal error, bad response).
    pub const TRUST_TOKEN_OPERATION_FAILED: Self = Self(-506);
    /// When handling a Trust Tokens protocol operation-executing request, the system was able to execute the request's Trust Tokens operation without sending the request to its destination: for instance, the results could have been present in a local cache (for redemption) or the operation could have been diverted to a local provider (for "platform-provided" issuance).
    pub const TRUST_TOKEN_OPERATION_SUCCESS_WITHOUT_SENDING_REQUEST: Self = Self(-507);
    /// This is a placeholder value that should never be used within //net. When Cronet APIs are being backed by HttpEngine (i.e., HttpEngineProvider is being used), org.chromium.net.NetworkException#getCronetInternalErrorCode is not supported (android.net.http.NetworkException#getCronetInternalErrorCode does not exist). In this scenario, getCronetInternalErrorCode will always return this error. This is a first step towards the deprecation of getCronetInternalErrorCode. Temporarily terminate, then restart, ITTT to avoid unsupported nesting. //tools/metrics/histograms/enums.xml:HTTPResponseAndNetErrorCodes, //tools/metrics/histograms/enums.xml:NetErrorCodes, )
    pub const HTTPENGINE_PROVIDER_IN_USE: Self = Self(-508);
    /// PKCS #12 import failed due to incorrect password.
    pub const PKCS12_IMPORT_BAD_PASSWORD: Self = Self(-701);
    /// PKCS #12 import failed due to other error.
    pub const PKCS12_IMPORT_FAILED: Self = Self(-702);
    /// CA import failed - not a CA cert.
    pub const IMPORT_CA_CERT_NOT_CA: Self = Self(-703);
    /// Import failed - certificate already exists in database. Note it's a little weird this is an error but reimporting a PKCS12 is ok (no-op).  That's how Mozilla does it, though.
    pub const IMPORT_CERT_ALREADY_EXISTS: Self = Self(-704);
    /// CA import failed due to some other error.
    pub const IMPORT_CA_CERT_FAILED: Self = Self(-705);
    /// Server certificate import failed due to some internal error.
    pub const IMPORT_SERVER_CERT_FAILED: Self = Self(-706);
    /// PKCS #12 import failed due to invalid MAC.
    pub const PKCS12_IMPORT_INVALID_MAC: Self = Self(-707);
    /// PKCS #12 import failed due to invalid/corrupt file.
    pub const PKCS12_IMPORT_INVALID_FILE: Self = Self(-708);
    /// PKCS #12 import failed due to unsupported features.
    pub const PKCS12_IMPORT_UNSUPPORTED: Self = Self(-709);
    /// Key generation failed.
    pub const KEY_GENERATION_FAILED: Self = Self(-710);
    /// Failure to export private key.
    pub const PRIVATE_KEY_EXPORT_FAILED: Self = Self(-712);
    /// Self-signed certificate generation failed.
    pub const SELF_SIGNED_CERT_GENERATION_FAILED: Self = Self(-713);
    /// The certificate database changed in some way.
    pub const CERT_DATABASE_CHANGED: Self = Self(-714);
    /// The certificate verifier configuration changed in some way.
    pub const CERT_VERIFIER_CHANGED: Self = Self(-716);
    /// DNS resolver received a malformed response.
    pub const DNS_MALFORMED_RESPONSE: Self = Self(-800);
    /// DNS server requires TCP
    pub const DNS_SERVER_REQUIRES_TCP: Self = Self(-801);
    /// DNS transaction timed out.
    pub const DNS_TIMED_OUT: Self = Self(-803);
    /// The entry was not found in cache or other local sources, for lookups where only local sources were queried. TODO(ericorth): Consider renaming to DNS_LOCAL_MISS or something like that as the cache is not necessarily queried either.
    pub const DNS_CACHE_MISS: Self = Self(-804);
    /// Suffix search list rules prevent resolution of the given host name.
    pub const DNS_SEARCH_EMPTY: Self = Self(-805);
    /// Failed to sort addresses according to RFC3484.
    pub const DNS_SORT_ERROR: Self = Self(-806);
    /// Failed to resolve the hostname of a DNS-over-HTTPS server.
    pub const DNS_SECURE_RESOLVER_HOSTNAME_RESOLUTION_FAILED: Self = Self(-808);
    /// DNS identified the request as disallowed for insecure connection (http/ws). Error should be handled as if an HTTP redirect was received to redirect to https or wss.
    pub const DNS_NAME_HTTPS_ONLY: Self = Self(-809);
    /// All DNS requests associated with this job have been cancelled.
    pub const DNS_REQUEST_CANCELLED: Self = Self(-810);
    /// The hostname resolution of HTTPS record was expected to be resolved with alpn values of supported protocols, but did not.
    pub const DNS_NO_MATCHING_SUPPORTED_ALPN: Self = Self(-811);
    /// When checking whether secure DNS can be used, the response returned for the requested probe record either had no answer or was invalid.
    pub const DNS_SECURE_PROBE_RECORD_INVALID: Self = Self(-814);
    /// Returned when DNS cache invalidation is in progress. This is a transient error. Callers may want to retry later.
    pub const DNS_CACHE_INVALIDATION_IN_PROGRESS: Self = Self(-815);
    /// The DNS server responded with a format error response code.
    pub const DNS_FORMAT_ERROR: Self = Self(-816);
    /// The DNS server responded with a server failure response code.
    pub const DNS_SERVER_FAILURE: Self = Self(-817);
    /// The DNS server responded that the query type is not implemented.
    pub const DNS_NOT_IMPLEMENTED: Self = Self(-818);
    /// The DNS server responded that the request was refused.
    pub const DNS_REFUSED: Self = Self(-819);
    /// The DNS server responded with an rcode indicating that the request failed, but the rcode is not one that we have a specific error code for. In other words, the rcode was not one of the following: - NOERR - FORMERR - SERVFAIL - NXDOMAIN - NOTIMP - REFUSED
    pub const DNS_OTHER_FAILURE: Self = Self(-820);
    /// Declined to call DNS for a direct_only request of a hostname whose traffic would be routed through a proxy.
    pub const DNS_DIRECT_ONLY: Self = Self(-821);
    /// The construction arguments are invalid. This is considered a bad IPC.
    pub const BLOB_INVALID_CONSTRUCTION_ARGUMENTS: Self = Self(-900);
    /// We don't have enough memory for the blob.
    pub const BLOB_OUT_OF_MEMORY: Self = Self(-901);
    /// We couldn't create or write to a file. File system error, like a full disk.
    pub const BLOB_FILE_WRITE_FAILED: Self = Self(-902);
    /// The renderer was destroyed while data was in transit.
    pub const BLOB_SOURCE_DIED_IN_TRANSIT: Self = Self(-903);
    /// The renderer destructed the blob before it was done transferring, and there were no outstanding references (no one is waiting to read) to keep the blob alive.
    pub const BLOB_DEREFERENCED_WHILE_BUILDING: Self = Self(-904);
    /// A blob that we referenced during construction is broken, or a browser-side builder tries to build a blob with a blob reference that isn't finished constructing.
    pub const BLOB_REFERENCED_BLOB_BROKEN: Self = Self(-905);
    /// A file that we referenced during construction is not accessible to the renderer trying to create the blob.
    pub const BLOB_REFERENCED_FILE_UNAVAILABLE: Self = Self(-906);
}

/// Every known error, sorted by code for binary search.
pub(super) static TABLE: [Entry; 248] = [
    Entry {
        code: -906,
        name: "ERR_BLOB_REFERENCED_FILE_UNAVAILABLE",
        description: "A file that we referenced during construction is not accessible to the renderer trying to create the blob.",
    },
    Entry {
        code: -905,
        name: "ERR_BLOB_REFERENCED_BLOB_BROKEN",
        description: "A blob that we referenced during construction is broken, or a browser-side builder tries to build a blob with a blob reference that isn't finished constructing.",
    },
    Entry {
        code: -904,
        name: "ERR_BLOB_DEREFERENCED_WHILE_BUILDING",
        description: "The renderer destructed the blob before it was done transferring, and there were no outstanding references (no one is waiting to read) to keep the blob alive.",
    },
    Entry {
        code: -903,
        name: "ERR_BLOB_SOURCE_DIED_IN_TRANSIT",
        description: "The renderer was destroyed while data was in transit.",
    },
    Entry {
        code: -902,
        name: "ERR_BLOB_FILE_WRITE_FAILED",
        description: "We couldn't create or write to a file. File system error, like a full disk.",
    },
    Entry {
        code: -901,
        name: "ERR_BLOB_OUT_OF_MEMORY",
        description: "We don't have enough memory for the blob.",
    },
    Entry {
        code: -900,
        name: "ERR_BLOB_INVALID_CONSTRUCTION_ARGUMENTS",
        description: "The construction arguments are invalid. This is considered a bad IPC.",
    },
    Entry {
        code: -821,
        name: "ERR_DNS_DIRECT_ONLY",
        description: "Declined to call DNS for a direct_only request of a hostname whose traffic would be routed through a proxy.",
    },
    Entry {
        code: -820,
        name: "ERR_DNS_OTHER_FAILURE",
        description: "The DNS server responded with an rcode indicating that the request failed, but the rcode is not one that we have a specific error code for. In other words, the rcode was not one of the following: - NOERR - FORMERR - SERVFAIL - NXDOMAIN - NOTIMP - REFUSED",
    },
    Entry {
        code: -819,
        name: "ERR_DNS_REFUSED",
        description: "The DNS server responded that the request was refused.",
    },
    Entry {
        code: -818,
        name: "ERR_DNS_NOT_IMPLEMENTED",
        description: "The DNS server responded that the query type is not implemented.",
    },
    Entry {
        code: -817,
        name: "ERR_DNS_SERVER_FAILURE",
        description: "The DNS server responded with a server failure response code.",
    },
    Entry {
        code: -816,
        name: "ERR_DNS_FORMAT_ERROR",
        description: "The DNS server responded with a format error response code.",
    },
    Entry {
        code: -815,
        name: "ERR_DNS_CACHE_INVALIDATION_IN_PROGRESS",
        description: "Returned when DNS cache invalidation is in progress. This is a transient error. Callers may want to retry later.",
    },
    Entry {
        code: -814,
        name: "ERR_DNS_SECURE_PROBE_RECORD_INVALID",
        description: "When checking whether secure DNS can be used, the response returned for the requested probe record either had no answer or was invalid.",
    },
    Entry {
        code: -811,
        name: "ERR_DNS_NO_MATCHING_SUPPORTED_ALPN",
        description: "The hostname resolution of HTTPS record was expected to be resolved with alpn values of supported protocols, but did not.",
    },
    Entry {
        code: -810,
        name: "ERR_DNS_REQUEST_CANCELLED",
        description: "All DNS requests associated with this job have been cancelled.",
    },
    Entry {
        code: -809,
        name: "ERR_DNS_NAME_HTTPS_ONLY",
        description: "DNS identified the request as disallowed for insecure connection (http/ws). Error should be handled as if an HTTP redirect was received to redirect to https or wss.",
    },
    Entry {
        code: -808,
        name: "ERR_DNS_SECURE_RESOLVER_HOSTNAME_RESOLUTION_FAILED",
        description: "Failed to resolve the hostname of a DNS-over-HTTPS server.",
    },
    Entry {
        code: -806,
        name: "ERR_DNS_SORT_ERROR",
        description: "Failed to sort addresses according to RFC3484.",
    },
    Entry {
        code: -805,
        name: "ERR_DNS_SEARCH_EMPTY",
        description: "Suffix search list rules prevent resolution of the given host name.",
    },
    Entry {
        code: -804,
        name: "ERR_DNS_CACHE_MISS",
        description: "The entry was not found in cache or other local sources, for lookups where only local sources were queried. TODO(ericorth): Consider renaming to DNS_LOCAL_MISS or something like that as the cache is not necessarily queried either.",
    },
    Entry {
        code: -803,
        name: "ERR_DNS_TIMED_OUT",
        description: "DNS transaction timed out.",
    },
    Entry {
        code: -801,
        name: "ERR_DNS_SERVER_REQUIRES_TCP",
        description: "DNS server requires TCP",
    },
    Entry {
        code: -800,
        name: "ERR_DNS_MALFORMED_RESPONSE",
        description: "DNS resolver received a malformed response.",
    },
    Entry {
        code: -716,
        name: "ERR_CERT_VERIFIER_CHANGED",
        description: "The certificate verifier configuration changed in some way.",
    },
    Entry {
        code: -714,
        name: "ERR_CERT_DATABASE_CHANGED",
        description: "The certificate database changed in some way.",
    },
    Entry {
        code: -713,
        name: "ERR_SELF_SIGNED_CERT_GENERATION_FAILED",
        description: "Self-signed certificate generation failed.",
    },
    Entry {
        code: -712,
        name: "ERR_PRIVATE_KEY_EXPORT_FAILED",
        description: "Failure to export private key.",
    },
    Entry {
        code: -710,
        name: "ERR_KEY_GENERATION_FAILED",
        description: "Key generation failed.",
    },
    Entry {
        code: -709,
        name: "ERR_PKCS12_IMPORT_UNSUPPORTED",
        description: "PKCS #12 import failed due to unsupported features.",
    },
    Entry {
        code: -708,
        name: "ERR_PKCS12_IMPORT_INVALID_FILE",
        description: "PKCS #12 import failed due to invalid/corrupt file.",
    },
    Entry {
        code: -707,
        name: "ERR_PKCS12_IMPORT_INVALID_MAC",
        description: "PKCS #12 import failed due to invalid MAC.",
    },
    Entry {
        code: -706,
        name: "ERR_IMPORT_SERVER_CERT_FAILED",
        description: "Server certificate import failed due to some internal error.",
    },
    Entry {
        code: -705,
        name: "ERR_IMPORT_CA_CERT_FAILED",
        description: "CA import failed due to some other error.",
    },
    Entry {
        code: -704,
        name: "ERR_IMPORT_CERT_ALREADY_EXISTS",
        description: "Import failed - certificate already exists in database. Note it's a little weird this is an error but reimporting a PKCS12 is ok (no-op).  That's how Mozilla does it, though.",
    },
    Entry {
        code: -703,
        name: "ERR_IMPORT_CA_CERT_NOT_CA",
        description: "CA import failed - not a CA cert.",
    },
    Entry {
        code: -702,
        name: "ERR_PKCS12_IMPORT_FAILED",
        description: "PKCS #12 import failed due to other error.",
    },
    Entry {
        code: -701,
        name: "ERR_PKCS12_IMPORT_BAD_PASSWORD",
        description: "PKCS #12 import failed due to incorrect password.",
    },
    Entry {
        code: -508,
        name: "ERR_HTTPENGINE_PROVIDER_IN_USE",
        description: "This is a placeholder value that should never be used within //net. When Cronet APIs are being backed by HttpEngine (i.e., HttpEngineProvider is being used), org.chromium.net.NetworkException#getCronetInternalErrorCode is not supported (android.net.http.NetworkException#getCronetInternalErrorCode does not exist). In this scenario, getCronetInternalErrorCode will always return this error. This is a first step towards the deprecation of getCronetInternalErrorCode. Temporarily terminate, then restart, ITTT to avoid unsupported nesting. //tools/metrics/histograms/enums.xml:HTTPResponseAndNetErrorCodes, //tools/metrics/histograms/enums.xml:NetErrorCodes, )",
    },
    Entry {
        code: -507,
        name: "ERR_TRUST_TOKEN_OPERATION_SUCCESS_WITHOUT_SENDING_REQUEST",
        description: "When handling a Trust Tokens protocol operation-executing request, the system was able to execute the request's Trust Tokens operation without sending the request to its destination: for instance, the results could have been present in a local cache (for redemption) or the operation could have been diverted to a local provider (for \"platform-provided\" issuance).",
    },
    Entry {
        code: -506,
        name: "ERR_TRUST_TOKEN_OPERATION_FAILED",
        description: "A Trust Tokens protocol operation-executing request failed for one of a number of reasons (precondition failure, internal error, bad response).",
    },
    Entry {
        code: -505,
        name: "ERR_INVALID_WEB_BUNDLE",
        description: "An error occurred while handling a Web Bundle source.",
    },
    Entry {
        code: -504,
        name: "ERR_INVALID_SIGNED_EXCHANGE",
        description: "An error occurred while handling a signed exchange.",
    },
    Entry {
        code: -503,
        name: "ERR_ADD_USER_CERT_FAILED",
        description: "An error adding a certificate to the OS certificate database.",
    },
    Entry {
        code: -502,
        name: "ERR_NO_PRIVATE_KEY_FOR_CERT",
        description: "An attempt to import a client certificate failed, as the user's key database lacked a corresponding private key.",
    },
    Entry {
        code: -501,
        name: "ERR_INSECURE_RESPONSE",
        description: "The server's response was insecure (e.g. there was a cert error).",
    },
    Entry {
        code: -414,
        name: "ERR_CACHE_COMPRESSION_FAILURE",
        description: "Zstd compression of a cache entry body failed.",
    },
    Entry {
        code: -413,
        name: "ERR_CACHE_OPEN_OR_CREATE_FAILURE",
        description: "The disk cache is unable to open or create this entry.",
    },
    Entry {
        code: -412,
        name: "ERR_CACHE_DOOM_FAILURE",
        description: "The disk cache is unable to doom this entry.",
    },
    Entry {
        code: -411,
        name: "ERR_CACHE_ENTRY_NOT_SUITABLE",
        description: "Internal not-quite error code for the HTTP cache. In-memory hints suggest that the cache entry would not have been usable with the transaction's current configuration (e.g. load flags, mode, etc.)",
    },
    Entry {
        code: -410,
        name: "ERR_CACHE_AUTH_FAILURE_AFTER_READ",
        description: "Received a challenge after the transaction has read some data, and the credentials aren't available.  There isn't a way to get them at that point.",
    },
    Entry {
        code: -409,
        name: "ERR_CACHE_LOCK_TIMEOUT",
        description: "Internal error code for the HTTP cache. The cache lock timeout has fired.",
    },
    Entry {
        code: -408,
        name: "ERR_CACHE_CHECKSUM_MISMATCH",
        description: "The cache found an entry with an invalid checksum. This can be returned from attempts to read from the cache. It is an internal error, returned by the SimpleCache backend, but not by any URLRequest methods or members.",
    },
    Entry {
        code: -407,
        name: "ERR_CACHE_CHECKSUM_READ_FAILURE",
        description: "The cache was unable to read a checksum record on an entry. This can be returned from attempts to read from the cache. It is an internal error, returned by the SimpleCache backend, but not by any URLRequest methods or members.",
    },
    Entry {
        code: -406,
        name: "ERR_CACHE_RACE",
        description: "Multiple transactions are racing to create disk cache entries. This is an internal error returned from the HttpCache to the HttpCacheTransaction that tells the transaction to restart the entry-creation logic because the state of the cache has changed.",
    },
    Entry {
        code: -405,
        name: "ERR_CACHE_CREATE_FAILURE",
        description: "The disk cache is unable to create this entry.",
    },
    Entry {
        code: -404,
        name: "ERR_CACHE_OPEN_FAILURE",
        description: "The disk cache is unable to open this entry.",
    },
    Entry {
        code: -403,
        name: "ERR_CACHE_OPERATION_NOT_SUPPORTED",
        description: "The operation is not supported for this entry.",
    },
    Entry {
        code: -402,
        name: "ERR_CACHE_WRITE_FAILURE",
        description: "Unable to write to the disk cache.",
    },
    Entry {
        code: -401,
        name: "ERR_CACHE_READ_FAILURE",
        description: "Unable to read from the disk cache.",
    },
    Entry {
        code: -400,
        name: "ERR_CACHE_MISS",
        description: "The cache does not have the requested entry.",
    },
    Entry {
        code: -388,
        name: "ERR_UNEXPECTED_CONTENT_DICTIONARY_HEADER",
        description: "The header of dictionary compressed stream does not match the expected value.",
    },
    Entry {
        code: -387,
        name: "ERR_DICTIONARY_LOAD_FAILED",
        description: "The compression dictionary cannot be loaded.",
    },
    Entry {
        code: -386,
        name: "ERR_ZSTD_WINDOW_SIZE_TOO_BIG",
        description: "Content decoding failed due to the zstd window size being too big (over 8MB).",
    },
    Entry {
        code: -385,
        name: "ERR_BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS",
        description: "The connection is blocked by private network access checks.",
    },
    Entry {
        code: -384,
        name: "ERR_CACHED_IP_ADDRESS_SPACE_BLOCKED_BY_LOCAL_NETWORK_ACCESS_POLICY",
        description: "The IP address space of the cached remote endpoint is blocked by private network access check.",
    },
    Entry {
        code: -383,
        name: "ERR_INCONSISTENT_IP_ADDRESS_SPACE",
        description: "The IP address space of the remote endpoint differed from the previous observed value during the same request. Any cache entry for the affected request should be invalidated.",
    },
    Entry {
        code: -382,
        name: "ERR_TOO_MANY_ACCEPT_CH_RESTARTS",
        description: "The ACCEPT_CH restart has been triggered too many times",
    },
    Entry {
        code: -381,
        name: "ERR_QUIC_GOAWAY_REQUEST_CAN_BE_RETRIED",
        description: "A GOAWAY frame has been received indicating that the request has not been processed and is therefore safe to retry on a different connection.",
    },
    Entry {
        code: -380,
        name: "ERR_QUIC_CERT_ROOT_NOT_KNOWN",
        description: "The certificate presented on a QUIC connection does not chain to a known root and the origin connected to is not on a list of domains where unknown roots are allowed.",
    },
    Entry {
        code: -379,
        name: "ERR_HTTP_RESPONSE_CODE_FAILURE",
        description: "The server returned a non-2xx HTTP response code. Note that this error is only used by certain APIs that interpret the HTTP response itself. URLRequest for instance just passes most non-2xx response back as success.",
    },
    Entry {
        code: -376,
        name: "ERR_HTTP2_STREAM_CLOSED",
        description: "Received an HTTP/2 frame on a closed stream.",
    },
    Entry {
        code: -375,
        name: "ERR_TOO_MANY_RETRIES",
        description: "An HTTP transaction was retried too many times due for authentication or invalid certificates. This may be due to a bug in the net stack that would otherwise infinite loop, or if the server or proxy continually requests fresh credentials or presents a fresh invalid certificate.",
    },
    Entry {
        code: -372,
        name: "ERR_HTTP2_RST_STREAM_NO_ERROR_RECEIVED",
        description: "Received HTTP/2 RST_STREAM frame with NO_ERROR error code.  This error should be handled internally by HTTP/2 code, and should not make it above the SpdyStream layer.",
    },
    Entry {
        code: -371,
        name: "ERR_CONTENT_DECODING_INIT_FAILED",
        description: "Initializing content decoding failed.",
    },
    Entry {
        code: -370,
        name: "ERR_INVALID_HTTP_RESPONSE",
        description: "The server was expected to return an HTTP/1.x response, but did not. Rather than treat it as HTTP/0.9, this error is returned.",
    },
    Entry {
        code: -367,
        name: "ERR_PAC_SCRIPT_TERMINATED",
        description: "The PAC script terminated fatally and must be reloaded.",
    },
    Entry {
        code: -366,
        name: "ERR_PROXY_HTTP_1_1_REQUIRED",
        description: "HTTP_1_1_REQUIRED error code received on HTTP/2 session to proxy.",
    },
    Entry {
        code: -365,
        name: "ERR_HTTP_1_1_REQUIRED",
        description: "HTTP_1_1_REQUIRED error code received on HTTP/2 session.",
    },
    Entry {
        code: -364,
        name: "ERR_PROXY_AUTH_REQUESTED_WITH_NO_CONNECTION",
        description: "Proxy Auth Requested without a valid Client Socket Handle.",
    },
    Entry {
        code: -363,
        name: "ERR_HTTP2_COMPRESSION_ERROR",
        description: "Decoding or encoding of compressed HTTP/2 headers failed.",
    },
    Entry {
        code: -362,
        name: "ERR_HTTP2_FRAME_SIZE_ERROR",
        description: "The peer sent an improperly sized HTTP/2 frame.",
    },
    Entry {
        code: -361,
        name: "ERR_HTTP2_FLOW_CONTROL_ERROR",
        description: "The peer violated HTTP/2 flow control.",
    },
    Entry {
        code: -360,
        name: "ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY",
        description: "Transport security is inadequate for the HTTP/2 version.",
    },
    Entry {
        code: -358,
        name: "ERR_QUIC_HANDSHAKE_FAILED",
        description: "The QUIC crypto handshake failed.  This means that the server was unable to read any requests sent, so they may be resent.",
    },
    Entry {
        code: -357,
        name: "ERR_RESPONSE_HEADERS_TRUNCATED",
        description: "The HTTP headers were truncated by an EOF.",
    },
    Entry {
        code: -356,
        name: "ERR_QUIC_PROTOCOL_ERROR",
        description: "There is a QUIC protocol error.",
    },
    Entry {
        code: -355,
        name: "ERR_INCOMPLETE_CHUNKED_ENCODING",
        description: "The HTTP response body is transferred with Chunked-Encoding, but the terminating zero-length chunk was never sent when the connection is closed.",
    },
    Entry {
        code: -354,
        name: "ERR_CONTENT_LENGTH_MISMATCH",
        description: "The HTTP response body transferred fewer bytes than were advertised by the Content-Length header when the connection is closed.",
    },
    Entry {
        code: -352,
        name: "ERR_HTTP2_PING_FAILED",
        description: "HTTP/2 server didn't respond to the PING message.",
    },
    Entry {
        code: -351,
        name: "ERR_HTTP2_SERVER_REFUSED_STREAM",
        description: "HTTP/2 server refused the request without processing, and sent either a GOAWAY frame with error code NO_ERROR and Last-Stream-ID lower than the stream id corresponding to the request indicating that this request has not been processed yet, or a RST_STREAM frame with error code REFUSED_STREAM. Client MAY retry (on a different connection).  See RFC7540 Section 8.1.4.",
    },
    Entry {
        code: -350,
        name: "ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION",
        description: "The HTTP response contained multiple Location headers.",
    },
    Entry {
        code: -349,
        name: "ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION",
        description: "The HTTP response contained multiple Content-Disposition headers.",
    },
    Entry {
        code: -348,
        name: "ERR_PAC_NOT_IN_DHCP",
        description: "No PAC URL configuration could be retrieved from DHCP. This can indicate either a failure to retrieve the DHCP configuration, or that there was no PAC URL configured in DHCP.",
    },
    Entry {
        code: -347,
        name: "ERR_INCOMPLETE_HTTP2_HEADERS",
        description: "HTTP/2 headers have been received, but not all of them - status or version headers are missing, so we're expecting additional frames to complete them.",
    },
    Entry {
        code: -346,
        name: "ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH",
        description: "The HTTP response contained multiple distinct Content-Length headers.",
    },
    Entry {
        code: -345,
        name: "ERR_RESPONSE_BODY_TOO_BIG_TO_DRAIN",
        description: "The HTTP response was too big to drain.",
    },
    Entry {
        code: -344,
        name: "ERR_UNDOCUMENTED_SECURITY_LIBRARY_STATUS",
        description: "An undocumented SSPI or GSSAPI status code was returned.",
    },
    Entry {
        code: -343,
        name: "ERR_MISCONFIGURED_AUTH_ENVIRONMENT",
        description: "The environment was not set up correctly for authentication (for example, no KDC could be found or the principal is unknown.",
    },
    Entry {
        code: -342,
        name: "ERR_UNEXPECTED_SECURITY_LIBRARY_STATUS",
        description: "An unexpected, but documented, SSPI or GSSAPI status code was returned.",
    },
    Entry {
        code: -341,
        name: "ERR_MISSING_AUTH_CREDENTIALS",
        description: "(GSSAPI) No Kerberos credentials were available during HTTP Authentication.",
    },
    Entry {
        code: -340,
        name: "ERR_ENCODING_DETECTION_FAILED",
        description: "Detecting the encoding of the response failed.",
    },
    Entry {
        code: -339,
        name: "ERR_UNSUPPORTED_AUTH_SCHEME",
        description: "An HTTP Authentication scheme was tried which is not supported on this machine.",
    },
    Entry {
        code: -338,
        name: "ERR_INVALID_AUTH_CREDENTIALS",
        description: "Credentials could not be established during HTTP Authentication.",
    },
    Entry {
        code: -337,
        name: "ERR_HTTP2_PROTOCOL_ERROR",
        description: "There is an HTTP/2 protocol error.",
    },
    Entry {
        code: -336,
        name: "ERR_NO_SUPPORTED_PROXIES",
        description: "There are no supported proxies in the provided list.",
    },
    Entry {
        code: -331,
        name: "ERR_NETWORK_IO_SUSPENDED",
        description: "An operation could not be completed because all network IO is suspended.",
    },
    Entry {
        code: -330,
        name: "ERR_CONTENT_DECODING_FAILED",
        description: "Content decoding of the response body failed.",
    },
    Entry {
        code: -329,
        name: "ERR_MALFORMED_IDENTITY",
        description: "The identity used for authentication is invalid.",
    },
    Entry {
        code: -328,
        name: "ERR_REQUEST_RANGE_NOT_SATISFIABLE",
        description: "The response was 416 (Requested range not satisfiable) and the server cannot satisfy the range requested.",
    },
    Entry {
        code: -327,
        name: "ERR_PAC_SCRIPT_FAILED",
        description: "The evaluation of the PAC script failed.",
    },
    Entry {
        code: -325,
        name: "ERR_RESPONSE_HEADERS_TOO_BIG",
        description: "The headers section of the response is too large.",
    },
    Entry {
        code: -324,
        name: "ERR_EMPTY_RESPONSE",
        description: "The server closed the connection without sending any data.",
    },
    Entry {
        code: -323,
        name: "ERR_UNEXPECTED_PROXY_AUTH",
        description: "The response was 407 (Proxy Authentication Required), yet we did not send the request to a proxy.",
    },
    Entry {
        code: -322,
        name: "ERR_METHOD_NOT_SUPPORTED",
        description: "The server did not support the request method.",
    },
    Entry {
        code: -321,
        name: "ERR_INVALID_CHUNKED_ENCODING",
        description: "Error in chunked transfer encoding.",
    },
    Entry {
        code: -320,
        name: "ERR_INVALID_RESPONSE",
        description: "The server's response was invalid.",
    },
    Entry {
        code: -312,
        name: "ERR_UNSAFE_PORT",
        description: "Attempting to load an URL with an unsafe port number.  These are port numbers that correspond to services, which are not robust to spurious input that may be constructed as a result of an allowed web construct (e.g., HTTP looks a lot like SMTP, so form submission to port 25 is denied).",
    },
    Entry {
        code: -311,
        name: "ERR_UNSAFE_REDIRECT",
        description: "Attempting to load an URL resulted in an unsafe redirect (e.g., a redirect to file:// is considered unsafe).",
    },
    Entry {
        code: -310,
        name: "ERR_TOO_MANY_REDIRECTS",
        description: "Attempting to load an URL resulted in too many redirects.",
    },
    Entry {
        code: -303,
        name: "ERR_INVALID_REDIRECT",
        description: "Attempting to load an URL resulted in a redirect to an invalid URL.",
    },
    Entry {
        code: -302,
        name: "ERR_UNKNOWN_URL_SCHEME",
        description: "The scheme of the URL is unknown.",
    },
    Entry {
        code: -301,
        name: "ERR_DISALLOWED_URL_SCHEME",
        description: "The scheme of the URL is disallowed.",
    },
    Entry {
        code: -300,
        name: "ERR_INVALID_URL",
        description: "The URL is invalid.",
    },
    Entry {
        code: -219,
        name: "ERR_CERT_SELF_SIGNED_LOCAL_NETWORK",
        description: "The certificate is self signed and it's being used for either an RFC1918 IP literal URL, or a url ending in .local.",
    },
    Entry {
        code: -217,
        name: "ERR_CERT_KNOWN_INTERCEPTION_BLOCKED",
        description: "The certificate is known to be used for interception by an entity other the device owner.",
    },
    Entry {
        code: -214,
        name: "ERR_CERTIFICATE_TRANSPARENCY_REQUIRED",
        description: "Certificate Transparency was required for this connection, but the server did not provide CT information that complied with the policy.",
    },
    Entry {
        code: -213,
        name: "ERR_CERT_VALIDITY_TOO_LONG",
        description: "The certificate's validity period is too long.",
    },
    Entry {
        code: -212,
        name: "ERR_CERT_NAME_CONSTRAINT_VIOLATION",
        description: "The certificate claimed DNS names that are in violation of name constraints.",
    },
    Entry {
        code: -211,
        name: "ERR_CERT_WEAK_KEY",
        description: "The server responded with a certificate that contains a weak key (e.g. a too-small RSA key).",
    },
    Entry {
        code: -210,
        name: "ERR_CERT_NON_UNIQUE_NAME",
        description: "The host name specified in the certificate is not unique.",
    },
    Entry {
        code: -208,
        name: "ERR_CERT_WEAK_SIGNATURE_ALGORITHM",
        description: "The server responded with a certificate that is signed using a weak signature algorithm.",
    },
    Entry {
        code: -207,
        name: "ERR_CERT_INVALID",
        description: "The server responded with a certificate that is invalid. This error is not recoverable. MSDN describes this error as follows: \"The SSL certificate is invalid.\"",
    },
    Entry {
        code: -206,
        name: "ERR_CERT_REVOKED",
        description: "The server responded with a certificate has been revoked. We have the capability to ignore this error, but it is probably not the thing to do.",
    },
    Entry {
        code: -205,
        name: "ERR_CERT_UNABLE_TO_CHECK_REVOCATION",
        description: "Revocation information for the security certificate for this site is not available.  This could mean: 1. An attacker has compromised the private key in the certificate and is blocking our attempt to find out that the cert was revoked. 2. The certificate is unrevoked, but the revocation server is busy or unavailable.",
    },
    Entry {
        code: -204,
        name: "ERR_CERT_NO_REVOCATION_MECHANISM",
        description: "The certificate has no mechanism for determining if it is revoked.  In effect, this certificate cannot be revoked.",
    },
    Entry {
        code: -203,
        name: "ERR_CERT_CONTAINS_ERRORS",
        description: "The server responded with a certificate that contains errors. This error is not recoverable. MSDN describes this error as follows: \"The SSL certificate contains errors.\" NOTE: It's unclear how this differs from ERR_CERT_INVALID. For consistency, use that code instead of this one from now on.",
    },
    Entry {
        code: -202,
        name: "ERR_CERT_AUTHORITY_INVALID",
        description: "The server responded with a certificate that is signed by an authority we don't trust.  The could mean: 1. An attacker has substituted the real certificate for a cert that contains their public key and is signed by their cousin. 2. The server operator has a legitimate certificate from a CA we don't know about, but should trust. 3. The server is presenting a self-signed certificate, providing no defense against active attackers (but foiling passive attackers).",
    },
    Entry {
        code: -201,
        name: "ERR_CERT_DATE_INVALID",
        description: "The server responded with a certificate that, by our clock, appears to either not yet be valid or to have expired.  This could mean: 1. An attacker is presenting an old certificate for which they have managed to obtain the private key. 2. The server is misconfigured and is not presenting a valid cert. 3. Our clock is wrong.",
    },
    Entry {
        code: -200,
        name: "ERR_CERT_COMMON_NAME_INVALID",
        description: "The server responded with a certificate whose common name did not match the host name.  This could mean: 1. An attacker has redirected our traffic to their server and is presenting a certificate for which they know the private key. 2. The server is misconfigured and responding with the wrong cert. 3. The user is on a wireless network and is being redirected to the network's login page. 4. The OS has used a DNS search suffix and the server doesn't have a certificate for the abbreviated name in the address bar.",
    },
    Entry {
        code: -190,
        name: "ERR_MULTICAST_NOT_ALLOWED",
        description: "Direct Sockets attempted to connect to or send a packet to a multicast address without 'direct-sockets-multicast' permissions policy.",
    },
    Entry {
        code: -189,
        name: "ERR_CONTROL_MSG_TOO_BIG",
        description: "The control message was too large for the transport. (for example a UDP message control data exceeds size threshold).",
    },
    Entry {
        code: -188,
        name: "ERR_PROXY_DELEGATE_CANCELED_CONNECT_RESPONSE",
        description: "",
    },
    Entry {
        code: -187,
        name: "ERR_PROXY_DELEGATE_CANCELED_CONNECT_REQUEST",
        description: "Some implementations of ProxyDelegate query a separate entity to know whether it should cancel tunnel prior to: - The HTTP CONNECT requests being sent out - The HTTP CONNECT response being parsed by //net An example is CronetProxyDelegate: Cronet allows developers to decide whether the tunnel being established should be canceled.",
    },
    Entry {
        code: -186,
        name: "ERR_PROXY_UNABLE_TO_CONNECT_TO_DESTINATION",
        description: "An attempt to proxy a request failed because the proxy wasn't able to successfully connect to the destination. This likely indicates an issue with the request itself (for instance, the hostname failed to resolve to an IP address or the destination server refused the connection). This error code is used to indicate that the error is outside the control of the proxy server and thus the proxy chain should not be marked as bad. This is in contrast to ERR_TUNNEL_CONNECTION_FAILED which is used for general purpose errors connecting to the proxy and by the proxy request response handling when a proxy delegate doesn't indicate via a different error code whether proxy fallback should occur. Note that for IP Protection proxies this error code causes the proxy to be marked as bad since the preference is to fail open for general purpose errors, but for other proxies this error does not cause the proxy to be marked as bad.",
    },
    Entry {
        code: -184,
        name: "ERR_ECH_FALLBACK_CERTIFICATE_INVALID",
        description: "ECH was enabled, the server was unable to decrypt the encrypted ClientHello, and additionally did not present a certificate valid for the public name.",
    },
    Entry {
        code: -183,
        name: "ERR_ECH_NOT_NEGOTIATED",
        description: "ECH was enabled, but the server was unable to decrypt the encrypted ClientHello.",
    },
    Entry {
        code: -182,
        name: "ERR_INVALID_ECH_CONFIG_LIST",
        description: "The ECHConfigList fetched over DNS cannot be parsed.",
    },
    Entry {
        code: -181,
        name: "ERR_SSL_KEY_USAGE_INCOMPATIBLE",
        description: "The server's certificate has a keyUsage extension incompatible with the negotiated TLS key exchange method.",
    },
    Entry {
        code: -180,
        name: "ERR_TLS13_DOWNGRADE_DETECTED",
        description: "TLS 1.3 was enabled, but a lower version was negotiated and the server returned a value indicating it supported TLS 1.3. This is part of a security check in TLS 1.3, but it may also indicate the user is behind a buggy TLS-terminating proxy which implemented TLS 1.2 incorrectly. (See https://crbug.com/boringssl/226.)",
    },
    Entry {
        code: -179,
        name: "ERR_WRONG_VERSION_ON_EARLY_DATA",
        description: "TLS 1.3 early data was offered, but the server responded with TLS 1.2 or earlier. This is an internal error code to account for a backwards-compatibility issue with early data and TLS 1.2. It will be received before any data is returned from the socket. The request should be retried with early data disabled. See https://tools.ietf.org/html/rfc8446#appendix-D.3 for details.",
    },
    Entry {
        code: -178,
        name: "ERR_EARLY_DATA_REJECTED",
        description: "TLS 1.3 early data was rejected by the server. This will be received before any data is returned from the socket. The request should be retried with early data disabled.",
    },
    Entry {
        code: -177,
        name: "ERR_SSL_CLIENT_AUTH_NO_COMMON_ALGORITHMS",
        description: "There were no common signature algorithms between our client certificate private key and the server's preferences.",
    },
    Entry {
        code: -176,
        name: "ERR_NO_BUFFER_SPACE",
        description: "No socket buffer space is available.",
    },
    Entry {
        code: -174,
        name: "ERR_READ_IF_READY_NOT_IMPLEMENTED",
        description: "Socket ReadIfReady support is not implemented. This error should not be user visible, because the normal Read() method is used as a fallback.",
    },
    Entry {
        code: -173,
        name: "ERR_WS_UPGRADE",
        description: "When a WebSocket handshake is done successfully and the connection has been upgraded, the URLRequest is cancelled with this error code.",
    },
    Entry {
        code: -172,
        name: "ERR_SSL_OBSOLETE_CIPHER",
        description: "The SSL server required an unsupported cipher suite that has since been removed. This error will temporarily be signaled on a fallback for one or two releases immediately following a cipher suite's removal, after which the fallback will be removed.",
    },
    Entry {
        code: -171,
        name: "ERR_CT_CONSISTENCY_PROOF_PARSING_FAILED",
        description: "Certificate Transparency: Failed to parse the received consistency proof.",
    },
    Entry {
        code: -170,
        name: "ERR_UNABLE_TO_REUSE_CONNECTION_FOR_PROXY_AUTH",
        description: "The attempt to reuse a connection to send proxy auth credentials failed before the AuthController was used to generate credentials. The caller should reuse the controller with a new connection. This error is only used internally by the network stack.",
    },
    Entry {
        code: -169,
        name: "ERR_CT_STH_INCOMPLETE",
        description: "Certificate Transparency: Received a signed tree head whose JSON parsing was OK but was missing some of the fields.",
    },
    Entry {
        code: -168,
        name: "ERR_CT_STH_PARSING_FAILED",
        description: "Certificate Transparency: Received a signed tree head that failed to parse.",
    },
    Entry {
        code: -167,
        name: "ERR_SSL_SERVER_CERT_BAD_FORMAT",
        description: "The SSL server presented a certificate which could not be decoded. This is not a certificate error code as no X509Certificate object is available. This error is fatal.",
    },
    Entry {
        code: -166,
        name: "ERR_ICANN_NAME_COLLISION",
        description: "Resolving a hostname to an IP address list included the IPv4 address \"127.0.53.53\". This is a special IP address which ICANN has recommended to indicate there was a name collision, and alert admins to a potential problem.",
    },
    Entry {
        code: -164,
        name: "ERR_SSL_CLIENT_AUTH_CERT_BAD_FORMAT",
        description: "Failed to import a client certificate from the platform store into the SSL library.",
    },
    Entry {
        code: -163,
        name: "ERR_SOCKET_SEND_BUFFER_SIZE_UNCHANGEABLE",
        description: "Failed to set the socket's send buffer size as requested, despite success return code from setsockopt.",
    },
    Entry {
        code: -162,
        name: "ERR_SOCKET_RECEIVE_BUFFER_SIZE_UNCHANGEABLE",
        description: "Failed to set the socket's receive buffer size as requested, despite success return code from setsockopt.",
    },
    Entry {
        code: -161,
        name: "ERR_SOCKET_SET_SEND_BUFFER_SIZE_ERROR",
        description: "Failed to set the socket's send buffer size as requested.",
    },
    Entry {
        code: -160,
        name: "ERR_SOCKET_SET_RECEIVE_BUFFER_SIZE_ERROR",
        description: "Failed to set the socket's receive buffer size as requested.",
    },
    Entry {
        code: -159,
        name: "ERR_SSL_UNRECOGNIZED_NAME_ALERT",
        description: "The SSL server sent us a fatal unrecognized_name alert.",
    },
    Entry {
        code: -156,
        name: "ERR_SSL_SERVER_CERT_CHANGED",
        description: "The SSL server certificate changed in a renegotiation.",
    },
    Entry {
        code: -154,
        name: "ERR_WS_THROTTLE_QUEUE_TOO_LARGE",
        description: "There are too many pending WebSocketJob instances, so the new job was not pushed to the queue.",
    },
    Entry {
        code: -153,
        name: "ERR_SSL_DECRYPT_ERROR_ALERT",
        description: "An SSL peer sent us a fatal decrypt_error alert. This typically occurs when a peer could not correctly verify a signature (in CertificateVerify or ServerKeyExchange) or validate a Finished message.",
    },
    Entry {
        code: -151,
        name: "ERR_CLIENT_AUTH_CERT_TYPE_UNSUPPORTED",
        description: "Server request for client certificate did not contain any types we support.",
    },
    Entry {
        code: -150,
        name: "ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN",
        description: "The certificate didn't match the built-in public key pins for the host name. The pins are set in net/http/transport_security_state.cc and require that one of a set of public keys exist on the path from the leaf to the root.",
    },
    Entry {
        code: -147,
        name: "ERR_ADDRESS_IN_USE",
        description: "Returned when attempting to bind an address that is already in use.",
    },
    Entry {
        code: -145,
        name: "ERR_WS_PROTOCOL_ERROR",
        description: "Websocket protocol error. Indicates that we are terminating the connection due to a malformed frame or other protocol violation.",
    },
    Entry {
        code: -142,
        name: "ERR_MSG_TOO_BIG",
        description: "The message was too large for the transport.  (for example a UDP message which exceeds size threshold).",
    },
    Entry {
        code: -141,
        name: "ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED",
        description: "We were unable to sign the CertificateVerify data of an SSL client auth handshake with the client certificate's private key. Possible causes for this include the user implicitly or explicitly denying access to the private key, the private key may not be valid for signing, the key may be relying on a cached handle which is no longer valid, or the CSP won't allow arbitrary data to be signed.",
    },
    Entry {
        code: -139,
        name: "ERR_TEMPORARILY_THROTTLED",
        description: "The request throttler module cancelled this request to avoid DDOS.",
    },
    Entry {
        code: -138,
        name: "ERR_NETWORK_ACCESS_DENIED",
        description: "Permission to access the network was denied. This is used to distinguish errors that were most likely caused by a firewall from other access denied errors. See also ERR_ACCESS_DENIED.",
    },
    Entry {
        code: -137,
        name: "ERR_NAME_RESOLUTION_FAILED",
        description: "An error occurred when trying to do a name resolution (DNS).",
    },
    Entry {
        code: -136,
        name: "ERR_PROXY_CERTIFICATE_INVALID",
        description: "The certificate presented by the HTTPS Proxy was invalid.",
    },
    Entry {
        code: -135,
        name: "ERR_SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY",
        description: "The SSL client certificate has no private key.",
    },
    Entry {
        code: -134,
        name: "ERR_SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED",
        description: "The permission to use the SSL client certificate's private key was denied.",
    },
    Entry {
        code: -133,
        name: "ERR_PRECONNECT_MAX_SOCKET_LIMIT",
        description: "We've hit the max socket limit for the socket pool while preconnecting.  We don't bother trying to preconnect more sockets.",
    },
    Entry {
        code: -131,
        name: "ERR_MANDATORY_PROXY_CONFIGURATION_FAILED",
        description: "A mandatory proxy configuration could not be used. Currently this means that a mandatory PAC script could not be fetched, parsed or executed.",
    },
    Entry {
        code: -130,
        name: "ERR_PROXY_CONNECTION_FAILED",
        description: "Could not create a connection to the proxy server. An error occurred either in resolving its name, or in connecting a socket to it. Note that this does NOT include failures during the actual \"CONNECT\" method of an HTTP proxy.",
    },
    Entry {
        code: -127,
        name: "ERR_PROXY_AUTH_REQUESTED",
        description: "The proxy requested authentication (for tunnel establishment).",
    },
    Entry {
        code: -126,
        name: "ERR_SSL_BAD_RECORD_MAC_ALERT",
        description: "An SSL peer sent us a fatal bad_record_mac alert. This has been observed from servers with buggy DEFLATE support.",
    },
    Entry {
        code: -125,
        name: "ERR_SSL_DECOMPRESSION_FAILURE_ALERT",
        description: "An SSL peer sent us a fatal decompression_failure alert. This typically occurs when a peer selects DEFLATE compression in the mistaken belief that it supports it.",
    },
    Entry {
        code: -124,
        name: "ERR_WINSOCK_UNEXPECTED_WRITTEN_BYTES",
        description: "Winsock sometimes reports more data written than passed.  This is probably due to a broken LSP.",
    },
    Entry {
        code: -123,
        name: "ERR_SSL_NO_RENEGOTIATION",
        description: "The peer sent an SSL no_renegotiation alert message.",
    },
    Entry {
        code: -122,
        name: "ERR_ALPN_NEGOTIATION_FAILED",
        description: "The request to negotiate an alternate protocol failed.",
    },
    Entry {
        code: -121,
        name: "ERR_SOCKS_CONNECTION_HOST_UNREACHABLE",
        description: "The SOCKS proxy server failed establishing connection to the target host because that host is unreachable.",
    },
    Entry {
        code: -120,
        name: "ERR_SOCKS_CONNECTION_FAILED",
        description: "Failed establishing a connection to the SOCKS proxy server for a target host.",
    },
    Entry {
        code: -119,
        name: "ERR_HOST_RESOLVER_QUEUE_TOO_LARGE",
        description: "There are too many pending DNS resolves, so a request in the queue was aborted.",
    },
    Entry {
        code: -118,
        name: "ERR_CONNECTION_TIMED_OUT",
        description: "A connection attempt timed out.",
    },
    Entry {
        code: -117,
        name: "ERR_BAD_SSL_CLIENT_AUTH_CERT",
        description: "The SSL handshake failed because of a bad or missing client certificate.",
    },
    Entry {
        code: -115,
        name: "ERR_PROXY_AUTH_UNSUPPORTED",
        description: "The proxy requested authentication (for tunnel establishment) with an unsupported method.",
    },
    Entry {
        code: -114,
        name: "ERR_SSL_RENEGOTIATION_REQUESTED",
        description: "The server requested a renegotiation (rehandshake).",
    },
    Entry {
        code: -113,
        name: "ERR_SSL_VERSION_OR_CIPHER_MISMATCH",
        description: "The client and server don't support a common SSL protocol version or cipher suite.",
    },
    Entry {
        code: -111,
        name: "ERR_TUNNEL_CONNECTION_FAILED",
        description: "A tunnel connection through the proxy could not be established. For more info see the comment on PROXY_UNABLE_TO_CONNECT_TO_DESTINATION.",
    },
    Entry {
        code: -110,
        name: "ERR_SSL_CLIENT_AUTH_CERT_NEEDED",
        description: "The server requested a client certificate for SSL client authentication.",
    },
    Entry {
        code: -109,
        name: "ERR_ADDRESS_UNREACHABLE",
        description: "The IP address is unreachable.  This usually means that there is no route to the specified host or network.",
    },
    Entry {
        code: -108,
        name: "ERR_ADDRESS_INVALID",
        description: "The IP address or port number is invalid (e.g., cannot connect to the IP address 0 or the port 0).",
    },
    Entry {
        code: -107,
        name: "ERR_SSL_PROTOCOL_ERROR",
        description: "An SSL protocol error occurred.",
    },
    Entry {
        code: -106,
        name: "ERR_INTERNET_DISCONNECTED",
        description: "The Internet connection has been lost.",
    },
    Entry {
        code: -105,
        name: "ERR_NAME_NOT_RESOLVED",
        description: "The host name could not be resolved.",
    },
    Entry {
        code: -104,
        name: "ERR_CONNECTION_FAILED",
        description: "A connection attempt failed.",
    },
    Entry {
        code: -103,
        name: "ERR_CONNECTION_ABORTED",
        description: "A connection timed out as a result of not receiving an ACK for data sent. This can include a FIN packet that did not get ACK'd.",
    },
    Entry {
        code: -102,
        name: "ERR_CONNECTION_REFUSED",
        description: "A connection attempt was refused.",
    },
    Entry {
        code: -101,
        name: "ERR_CONNECTION_RESET",
        description: "A connection was reset (corresponding to a TCP RST).",
    },
    Entry {
        code: -100,
        name: "ERR_CONNECTION_CLOSED",
        description: "A connection was closed (corresponding to a TCP FIN).",
    },
    Entry {
        code: -37,
        name: "ERR_STRICT_ECH_REQUIRED",
        description: "The request was blocked because ECH is strictly required, but: - The client could not obtain a valid ECH configuration. - The server rejected the ECH, and the client failed to establish a new ECH connection after retrying with retry_configs.",
    },
    Entry {
        code: -36,
        name: "ERR_LOCAL_NETWORK_PERMISSION_MISSING",
        description: "The request was blocked because the local network permission is missing. Note that this is different from BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS which is specifically for a CORS error code.",
    },
    Entry {
        code: -35,
        name: "ERR_BLOCKED_IN_INCOGNITO_BY_ADMINISTRATOR",
        description: "The request was blocked by the Incognito Mode URL block list configured by the domain administrator.",
    },
    Entry {
        code: -34,
        name: "ERR_BLOCKED_BY_FINGERPRINTING_PROTECTION",
        description: "The request was blocked by fingerprinting protections.",
    },
    Entry {
        code: -33,
        name: "ERR_NETWORK_ACCESS_REVOKED",
        description: "The request was blocked because it originated from a frame that has disabled network access.",
    },
    Entry {
        code: -32,
        name: "ERR_BLOCKED_BY_ORB",
        description: "The request was blocked by CORB or ORB.",
    },
    Entry {
        code: -30,
        name: "ERR_BLOCKED_BY_CSP",
        description: "The request was blocked by a Content Security Policy",
    },
    Entry {
        code: -29,
        name: "ERR_CLEARTEXT_NOT_PERMITTED",
        description: "The request was blocked by system policy disallowing some or all cleartext requests. Used for NetworkSecurityPolicy on Android.",
    },
    Entry {
        code: -27,
        name: "ERR_BLOCKED_BY_RESPONSE",
        description: "The request failed because the response was delivered along with requirements which are not met ('X-Frame-Options' and 'Content-Security-Policy' ancestor checks and 'Cross-Origin-Resource-Policy' for instance).",
    },
    Entry {
        code: -26,
        name: "ERR_CONTEXT_SHUT_DOWN",
        description: "The request failed because the URLRequestContext is shutting down, or has been shut down.",
    },
    Entry {
        code: -25,
        name: "ERR_UPLOAD_STREAM_REWIND_NOT_SUPPORTED",
        description: "The upload failed because the upload stream needed to be re-read, due to a retry or a redirect, but the upload stream doesn't support that operation.",
    },
    Entry {
        code: -23,
        name: "ERR_SOCKET_IS_CONNECTED",
        description: "The socket is already connected.",
    },
    Entry {
        code: -22,
        name: "ERR_BLOCKED_BY_ADMINISTRATOR",
        description: "The request was blocked by the URL block list configured by the domain administrator.",
    },
    Entry {
        code: -21,
        name: "ERR_NETWORK_CHANGED",
        description: "The network changed.",
    },
    Entry {
        code: -20,
        name: "ERR_BLOCKED_BY_CLIENT",
        description: "The client chose to block the request.",
    },
    Entry {
        code: -19,
        name: "ERR_FILE_VIRUS_INFECTED",
        description: "The file has a virus.",
    },
    Entry {
        code: -18,
        name: "ERR_FILE_NO_SPACE",
        description: "Not enough room left on the disk.",
    },
    Entry {
        code: -17,
        name: "ERR_FILE_PATH_TOO_LONG",
        description: "The path or file name is too long.",
    },
    Entry {
        code: -16,
        name: "ERR_FILE_EXISTS",
        description: "The file already exists.",
    },
    Entry {
        code: -15,
        name: "ERR_SOCKET_NOT_CONNECTED",
        description: "The socket is not connected.",
    },
    Entry {
        code: -14,
        name: "ERR_UPLOAD_FILE_CHANGED",
        description: "The file upload failed because the file's modification time was different from the expectation.",
    },
    Entry {
        code: -13,
        name: "ERR_OUT_OF_MEMORY",
        description: "Memory allocation failed.",
    },
    Entry {
        code: -12,
        name: "ERR_INSUFFICIENT_RESOURCES",
        description: "There were not enough resources to complete the operation.",
    },
    Entry {
        code: -11,
        name: "ERR_NOT_IMPLEMENTED",
        description: "The operation failed because of unimplemented functionality.",
    },
    Entry {
        code: -10,
        name: "ERR_ACCESS_DENIED",
        description: "Permission to access a resource, other than the network, was denied.",
    },
    Entry {
        code: -9,
        name: "ERR_UNEXPECTED",
        description: "An unexpected error.  This may be caused by a programming mistake or an invalid assumption.",
    },
    Entry {
        code: -8,
        name: "ERR_FILE_TOO_BIG",
        description: "The file is too large.",
    },
    Entry {
        code: -7,
        name: "ERR_TIMED_OUT",
        description: "An operation timed out.",
    },
    Entry {
        code: -6,
        name: "ERR_FILE_NOT_FOUND",
        description: "The file or directory cannot be found.",
    },
    Entry {
        code: -5,
        name: "ERR_INVALID_HANDLE",
        description: "The handle or file descriptor is invalid.",
    },
    Entry {
        code: -4,
        name: "ERR_INVALID_ARGUMENT",
        description: "An argument to the function is incorrect.",
    },
    Entry {
        code: -3,
        name: "ERR_ABORTED",
        description: "An operation was aborted (due to user action).",
    },
    Entry {
        code: -2,
        name: "ERR_FAILED",
        description: "A generic failure occurred.",
    },
    Entry {
        code: -1,
        name: "ERR_IO_PENDING",
        description: "An asynchronous IO operation is not yet complete.  This usually does not indicate a fatal error.  Typically this error will be generated as a notification to wait for some external notification that the IO operation finally completed.",
    },
];
