//! `cargo xtask net-errors`: Chromium's `net/base/net_error_list.h` becomes
//! the constants and lookup table of `cronet::NetError`.

use std::{fmt::Write as _, fs, path::PathBuf, sync::LazyLock};

use anyhow::{Context, Result};
use regex::Regex;

use crate::{Workspace, rustfmt};

static NET_ERROR: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"^NET_ERROR\((\w+),\s*(-\d+)\)").unwrap());

#[derive(Debug, PartialEq)]
struct Entry {
    name: String,
    code: i32,
    description: String,
}

pub(crate) fn run(workspace: &Workspace, source: Option<PathBuf>) -> Result<()> {
    let source = source.unwrap_or_else(|| workspace.src_root().join("net/base/net_error_list.h"));
    let text = fs::read_to_string(&source).with_context(|| format!("reading {}", source.display()))?;
    let entries = parse(&text);
    let output = workspace.root().join("crates/cronet/src/net_error/generated.rs");
    fs::write(&output, render(&entries))?;
    rustfmt(&output)?;
    eprintln!("wrote {} ({} error codes)", output.display(), entries.len());
    Ok(())
}

/// Every `NET_ERROR(NAME, code)`, described by the comment lines directly
/// above it. Anything else between them, a blank line included, starts the
/// comment over, so file and section headers describe nothing. `CERT_END`
/// marks the end of a range rather than naming an error.
fn parse(text: &str) -> Vec<Entry> {
    let mut entries = Vec::new();
    let mut comment: Vec<&str> = Vec::new();
    for line in text.lines().map(str::trim) {
        if let Some(text) = line.strip_prefix("//") {
            let text = text.trim();
            if !text.is_empty() && !text.starts_with("LINT.") {
                comment.push(text);
            }
            continue;
        }
        if let Some(captures) = NET_ERROR.captures(line)
            && captures[1] != *"CERT_END"
        {
            entries.push(Entry {
                name: captures[1].to_owned(),
                code: captures[2].parse().expect("the pattern only matches integers"),
                description: comment.join(" "),
            });
        }
        comment.clear();
    }
    entries
}

/// Rustdoc reads `[x]` as a link and `<x>` as HTML; neither is meant here.
/// URLs become links.
fn escape_doc(text: &str) -> String {
    let words: Vec<String> = text
        .split(' ')
        .map(|word| {
            if word.starts_with("http://") || word.starts_with("https://") {
                let url = word.trim_end_matches(['.', ',', ')']);
                return format!("<{url}>{}", &word[url.len()..]);
            }
            let mut escaped = String::with_capacity(word.len());
            for c in word.chars() {
                if matches!(c, '[' | ']' | '<' | '>' | '*' | '`') {
                    escaped.push('\\');
                }
                escaped.push(c);
            }
            escaped
        })
        .collect();
    words.join(" ")
}

fn render(entries: &[Entry]) -> String {
    let mut constants = String::new();
    for entry in entries {
        if !entry.description.is_empty() {
            writeln!(constants, "    /// {}", escape_doc(&entry.description)).unwrap();
        }
        writeln!(constants, "    pub const {}: Self = Self({});", entry.name, entry.code).unwrap();
    }

    let mut sorted: Vec<&Entry> = entries.iter().collect();
    sorted.sort_by_key(|entry| entry.code);
    let mut table = String::new();
    for entry in &sorted {
        writeln!(
            table,
            "    Entry {{ code: {}, name: {:?}, description: {:?} }},",
            entry.code,
            format!("ERR_{}", entry.name),
            entry.description,
        )
        .unwrap();
    }

    format!(
        "// @generated by `cargo xtask net-errors` from Chromium's `net/base/net_error_list.h`.\n\
         // Do not edit.\n\n\
         use super::{{Entry, NetError}};\n\n\
         impl NetError {{\n{constants}}}\n\n\
         /// Every known error, sorted by code for binary search.\n\
         pub(super) static TABLE: [Entry; {}] = [\n{table}];\n",
        sorted.len()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
// Copyright 2012 The Chromium Authors
// no-include-guard-because-multiply-included

//
// Ranges:
//     0- 99 System related errors

// LINT.IfChange

// An asynchronous IO operation is not yet complete.  This usually does not
// indicate a fatal error.
NET_ERROR(IO_PENDING, -1)

// Error -24 was removed (BLOCKED_ENROLLMENT_CHECK_PENDING)

// A connection attempt was refused.
NET_ERROR(CONNECTION_REFUSED, -102)
NET_ERROR(UNDOCUMENTED, -103)

// Update the value of CERT_END whenever you add a new certificate error
NET_ERROR(CERT_END, -220)
";

    #[test]
    fn docs_escape_markup_and_link_urls() {
        assert_eq!(
            escape_doc("See https://example.com/x#y. A [b] <c> *d*"),
            r"See <https://example.com/x#y>. A \[b\] \<c\> \*d\*"
        );
    }

    #[test]
    fn only_adjacent_comments_describe() {
        assert_eq!(
            parse(SAMPLE),
            [
                Entry {
                    name: "IO_PENDING".into(),
                    code: -1,
                    description: "An asynchronous IO operation is not yet complete.  This usually does not indicate a \
                                  fatal error."
                        .into(),
                },
                Entry {
                    name: "CONNECTION_REFUSED".into(),
                    code: -102,
                    description: "A connection attempt was refused.".into()
                },
                Entry {
                    name: "UNDOCUMENTED".into(),
                    code: -103,
                    description: String::new()
                },
            ]
        );
    }
}
